/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_SoundOutStateMaschine_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_SoundOutStateMaschine_Automatic
 *
 **/
#include "components_SoundOutStateMaschine_Automatic.l1.h"
#include "components_SoundOutStateMaschine_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_SoundOutStateMaschine_Automatic (L1_components_SoundOutStateMaschine_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
static ASDClassHeader L1_components_SoundOutStateMaschine_Automatic_ClassHeader = {
	0, 0, 6, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_SoundOutStateMaschine_Automatic_Class L1_components_SoundOutStateMaschine_Automatic_ClassObj = {{1, {&L1_components_SoundOutStateMaschine_Automatic_ClassHeader}, {0}}};

bool initialized_components_SoundOutStateMaschine_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_SoundOutStateMaschine_Automatic_Obj* initInstance_L1_components_SoundOutStateMaschine_Automatic(const struct components_SoundOutStateMaschine_Automatic* self)
{
    struct L1_components_SoundOutStateMaschine_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_SoundOutStateMaschine_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_SoundOutStateMaschine_Automatic = true;
        initClass_L1_components_SoundOutStateMaschine_Automatic(&L1_components_SoundOutStateMaschine_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_SoundOutStateMaschine_Automatic);
    L1_Instance->sm = initInstance_scalarWrapper((uint32)&sm_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->deltaTime = initInstance_scalarWrapper((uint32)&deltaTime_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->time = initInstance_scalarWrapper((uint32)&time_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->countShort = initInstance_scalarWrapper((uint32)&countShort_VAL, sizeof(sint32), ASD_VARIABLE);
    L1_Instance->countLong = initInstance_scalarWrapper((uint32)&countLong_VAL, sizeof(sint32), ASD_VARIABLE);
    L1_Instance->lampOn = initInstance_scalarWrapper((uint32)&lampOn_VAL, sizeof(uint8), ASD_VARIABLE);

    return L1_Instance;
}
