#ifndef _STRUCTURE_ASD_L1_components_SoundOutStateMaschine_Automatic
#define _STRUCTURE_ASD_L1_components_SoundOutStateMaschine_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_SoundOutStateMaschine_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_SoundOutStateMaschine_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_SoundOutStateMaschine_Automatic.h"

/**
 * local variables object structure 
 **/
struct L1_components_SoundOutStateMaschine_Automatic_Obj {
	ASDObjectHeader objectHeader;
	scalarWrapper_Obj* sm;
	scalarWrapper_Obj* deltaTime;
	scalarWrapper_Obj* time;
	scalarWrapper_Obj* countShort;
	scalarWrapper_Obj* countLong;
	scalarWrapper_Obj* lampOn;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_components_SoundOutStateMaschine_Automatic_Class;

extern L1_components_SoundOutStateMaschine_Automatic_Class L1_components_SoundOutStateMaschine_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_SoundOutStateMaschine_Automatic (L1_components_SoundOutStateMaschine_Automatic_Class* _ASCET_class);
extern struct L1_components_SoundOutStateMaschine_Automatic_Obj* initInstance_L1_components_SoundOutStateMaschine_Automatic(const struct components_SoundOutStateMaschine_Automatic* self);
#endif /* _STRUCTURE_ASD_L1_components_SoundOutStateMaschine_Automatic */
