/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Component_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_Component_Automatic
 *
 **/
#include "components_Component_Automatic.l1.h"
#include "components_Component_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_Component_Automatic (L1_components_Component_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_components_Component_Automatic_Obj* L1_components_Component_AutomaticInstance = NULL;

static ASDClassHeader L1_components_Component_Automatic_ClassHeader = {
	0, 0, 4, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_Component_Automatic_Class L1_components_Component_Automatic_ClassObj = {{1, {&L1_components_Component_Automatic_ClassHeader}, {0}}};

bool initialized_components_Component_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_Component_Automatic_Obj* initInstance_L1_components_Component_Automatic(void)
{
    struct L1_components_Component_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_Component_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_Component_Automatic = true;
        initClass_L1_components_Component_Automatic(&L1_components_Component_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_Component_Automatic);
    L1_Instance->Integrator_instance = initInstance_L1_components_lib_Integrator_Automatic(&Integrator_instance_VAL);
    L1_Instance->Integrator_instance1 = initInstance_L1_components_lib_Integrator_Automatic(&Integrator_instance1_VAL);
    L1_Instance->Integrator_instance2 = initInstance_L1_components_lib_Integrator_Automatic(&Integrator_instance2_VAL);
    L1_Instance->Integrator_instance3 = initInstance_L1_components_lib_Integrator_Automatic(&Integrator_instance3_VAL);
    L1_components_Component_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
