#ifndef _STRUCTURE_ASD_L1_components_veloCar_Automatic
#define _STRUCTURE_ASD_L1_components_veloCar_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_veloCar_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_veloCar_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_veloCar_Automatic.h"

/**
 * local variables object structure 
 **/
struct L1_components_veloCar_Automatic_Obj {
	ASDObjectHeader objectHeader;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
	scalarWrapper_Obj* vfl;
	scalarWrapper_Obj* vfr;
	scalarWrapper_Obj* vrl;
	scalarWrapper_Obj* vrr;
} L1_components_veloCar_Automatic_Class;

extern L1_components_veloCar_Automatic_Class L1_components_veloCar_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_veloCar_Automatic (L1_components_veloCar_Automatic_Class* _ASCET_class);
extern struct L1_components_veloCar_Automatic_Obj* initInstance_L1_components_veloCar_Automatic(void);
#endif /* _STRUCTURE_ASD_L1_components_veloCar_Automatic */
