/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_lib_diffCheck_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_lib_diffCheck_Automatic
 *
 **/
#include "components_lib_diffCheck_Automatic.l1.h"
#include "components_lib_diffCheck_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_lib_diffCheck_Automatic (L1_components_lib_diffCheck_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_components_lib_diffCheck_Automatic_Obj* L1_components_lib_diffCheck_AutomaticInstance = NULL;

static ASDClassHeader L1_components_lib_diffCheck_Automatic_ClassHeader = {
	0, 0, 1, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_lib_diffCheck_Automatic_Class L1_components_lib_diffCheck_Automatic_ClassObj = {{1, {&L1_components_lib_diffCheck_Automatic_ClassHeader}, {0}}};

bool initialized_components_lib_diffCheck_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_lib_diffCheck_Automatic_Obj* initInstance_L1_components_lib_diffCheck_Automatic(void)
{
    struct L1_components_lib_diffCheck_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_lib_diffCheck_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_lib_diffCheck_Automatic = true;
        initClass_L1_components_lib_diffCheck_Automatic(&L1_components_lib_diffCheck_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_lib_diffCheck_Automatic);
    L1_Instance->border = initInstance_scalarWrapper((uint32)&border_VAL, sizeof(float32), ASD_PARAMETER);
    L1_components_lib_diffCheck_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
