/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_distanceCar_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_distanceCar_Automatic
 *
 **/
#include "components_distanceCar_Automatic.l1.h"
#include "components_distanceCar_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_distanceCar_Automatic (L1_components_distanceCar_Automatic_Class* _ASCET_class)
{
    _ASCET_class->sfl = initInstance_scalarWrapper((uint32)&components_distanceCar_sfl_VAL, sizeof(float32), ASD_VARIABLE);
    _ASCET_class->sfr = initInstance_scalarWrapper((uint32)&components_distanceCar_sfr_VAL, sizeof(float32), ASD_VARIABLE);
    _ASCET_class->srl = initInstance_scalarWrapper((uint32)&components_distanceCar_srl_VAL, sizeof(float32), ASD_VARIABLE);
    _ASCET_class->srr = initInstance_scalarWrapper((uint32)&components_distanceCar_srr_VAL, sizeof(float32), ASD_VARIABLE);
    _ASCET_class->avgDistanceCar = initInstance_scalarWrapper((uint32)&components_distanceCar_avgDistanceCar_VAL, sizeof(float32), ASD_VARIABLE);
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_components_distanceCar_Automatic_Obj* L1_components_distanceCar_AutomaticInstance = NULL;

static ASDClassHeader L1_components_distanceCar_Automatic_ClassHeader = {
	0, 0, 0, 5, &_ObjectMethodList, &_ClassMethodList
};

L1_components_distanceCar_Automatic_Class L1_components_distanceCar_Automatic_ClassObj = {{1, {&L1_components_distanceCar_Automatic_ClassHeader}, {0}}};

bool initialized_components_distanceCar_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_distanceCar_Automatic_Obj* initInstance_L1_components_distanceCar_Automatic(void)
{
    struct L1_components_distanceCar_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_distanceCar_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_distanceCar_Automatic = true;
        initClass_L1_components_distanceCar_Automatic(&L1_components_distanceCar_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_distanceCar_Automatic);
    L1_components_distanceCar_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
