#ifndef _STRUCTURE_ASD_L1_components_Component_Automatic
#define _STRUCTURE_ASD_L1_components_Component_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Component_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_Component_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_Component_Automatic.h"
#include "components_lib_Integrator_Automatic.l1.h"

/**
 * local variables object structure 
 **/
struct L1_components_Component_Automatic_Obj {
	ASDObjectHeader objectHeader;
	struct L1_components_lib_Integrator_Automatic_Obj* Integrator_instance;
	struct L1_components_lib_Integrator_Automatic_Obj* Integrator_instance1;
	struct L1_components_lib_Integrator_Automatic_Obj* Integrator_instance2;
	struct L1_components_lib_Integrator_Automatic_Obj* Integrator_instance3;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_components_Component_Automatic_Class;

extern L1_components_Component_Automatic_Class L1_components_Component_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_Component_Automatic (L1_components_Component_Automatic_Class* _ASCET_class);
extern struct L1_components_Component_Automatic_Obj* initInstance_L1_components_Component_Automatic(void);
#endif /* _STRUCTURE_ASD_L1_components_Component_Automatic */
