/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    PC_PC.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for project L1 node: PC_PC
 *
 **/
#include "PC_PC.l1.h"
#include "PC_PC.init.h"
#include "programId_PC_PC.h"

/**
 * Class initialization 
 **/
void initClass_L1_PC_PC (L1_PC_PC_Class* _ASCET_class)
{
    _ASCET_class->components_lib_IntegratorTest_Automatic = initInstance_L1_components_lib_IntegratorTest_Automatic();
    _ASCET_class->components_Component_Automatic = initInstance_L1_components_Component_Automatic();
    _ASCET_class->components_veloCar_Automatic = initInstance_L1_components_veloCar_Automatic();
    _ASCET_class->components_distanceCar_Automatic = initInstance_L1_components_distanceCar_Automatic();
    _ASCET_class->components_diffWheel_Automatic = initInstance_L1_components_diffWheel_Automatic();
    _ASCET_class->components_pressureError_Automatic = initInstance_L1_components_pressureError_Automatic();
    _ASCET_class->components_lib_diffCheck_Automatic = initInstance_L1_components_lib_diffCheck_Automatic();
}

/**
 * L1 protocol functions 
 **/

static uint8 *_L1_getPid (ASDObject *self, uint8 *_ASCET_data)
{
    uint8 defineFlag = true;
    uint32 pid = UNIQUE_PROGRAM_ID;
    addScalar (_ASCET_data, (uint8 *)&pid, sizeof(uint32));
    addScalar (_ASCET_data, (uint8 *)&defineFlag, sizeof(defineFlag));
    return (_ASCET_data);
}

static uint8 *_L1_getNVid(ASDObject *self, uint8 *_ASCET_data)
{
    uint8 defineFlag = true;
    uint32 nvid = 0;
    addScalar (_ASCET_data, (uint8 *)&nvid, sizeof(nvid));
    addScalar (_ASCET_data, (uint8 *)&defineFlag, sizeof(defineFlag));
    return (_ASCET_data);
}

static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    _L1_getPid,
    _L1_getNVid
};

/**
 * Global objects 
 **/
struct L1_PC_PC_Obj* L1_PC_PCInstance = NULL;

static ASDClassHeader L1_PC_PC_ClassHeader = {
	0, 2, 0, 7, &_ObjectMethodList, &_ClassMethodList
};

L1_PC_PC_Class L1_PC_PC_ClassObj = {{1, {&L1_PC_PC_ClassHeader}, {0}}};

bool initialized_PC_PC = false;

/**
 * Initialize this L1 component 
 **/
struct L1_PC_PC_Obj* initInstance_L1_PC_PC(void)
{
    struct L1_PC_PC_Obj* L1_Instance = NULL;
    if (!initialized_PC_PC) {
        /* for first time also static class data shall be initialized */
        initialized_PC_PC = true;
        initClass_L1_PC_PC(&L1_PC_PC_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_PC_PC);
    L1_PC_PCInstance = L1_Instance;

    return L1_Instance;
}
