#ifndef _COMPONENTS_DISTANCECAR_AUTOMATIC_H_
#define _COMPONENTS_DISTANCECAR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_distanceCar_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_distanceCar
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_distanceCar_sfl_VAL components_distanceCar_sfl
#define components_distanceCar_sfr_VAL components_distanceCar_sfr
#define components_distanceCar_srl_VAL components_distanceCar_srl
#define components_distanceCar_srr_VAL components_distanceCar_srr
#define components_distanceCar_avgDistanceCar_VAL components_distanceCar_avgDistanceCar
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_DISTANCECAR_AUTOMATIC_H_ */
