#ifndef _COMPONENTS_COMPONENT_AUTOMATIC_H_
#define _COMPONENTS_COMPONENT_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Component_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Component
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define average_instance_VAL average_instance_components_Component
#define average_instance_REF &(average_instance_components_Component)
#define Integrator_instance_VAL components_Component.Integrator_instance
#define Integrator_instance_REF &(components_Component.Integrator_instance)
#define Integrator_instance1_VAL components_Component.Integrator_instance1
#define Integrator_instance1_REF &(components_Component.Integrator_instance1)
#define Integrator_instance2_VAL components_Component.Integrator_instance2
#define Integrator_instance2_REF &(components_Component.Integrator_instance2)
#define Integrator_instance3_VAL components_Component.Integrator_instance3
#define Integrator_instance3_REF &(components_Component.Integrator_instance3)
#define percentCompare_instance_VAL components_Component.percentCompare_instance
#define percentCompare_instance_REF &(components_Component.percentCompare_instance)
#define percentCompare_instance1_VAL components_Component.percentCompare_instance1
#define percentCompare_instance1_REF &(components_Component.percentCompare_instance1)
#define percentCompare_instance2_VAL components_Component.percentCompare_instance2
#define percentCompare_instance2_REF &(components_Component.percentCompare_instance2)
#define percentCompare_instance3_VAL components_Component.percentCompare_instance3
#define percentCompare_instance3_REF &(components_Component.percentCompare_instance3)
#define vflA_VAL components_Component_CAL_MEM.vflA
#define vflC_VAL components_Component_CAL_MEM.vflC
#define vflM_VAL components_Component_CAL_MEM.vflM
#define gain_VAL components_Component_CAL_MEM.gain
#define TirePressureProject_instance_VAL components_Component.TirePressureProject_instance
#define TirePressureProject_instance_REF &(components_Component.TirePressureProject_instance)
#define NoiseGenerator_instance_VAL components_Component.NoiseGenerator_instance
#define NoiseGenerator_instance_REF &(components_Component.NoiseGenerator_instance)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_COMPONENT_AUTOMATIC_H_ */
