/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_diffWheel_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:39:24
*
* @brief   "components_diffWheel>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_diffWheel_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_diffWheel'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................16
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'components_diffWheel_diffFl' */
float32 components_diffWheel_diffFl = 0.0F;
/* modelled as 'components_diffWheel_diffFr' */
float32 components_diffWheel_diffFr = 0.0F;
/* modelled as 'components_diffWheel_diffRl' */
float32 components_diffWheel_diffRl = 0.0F;
/* modelled as 'components_diffWheel_diffRr' */
float32 components_diffWheel_diffRr = 0.0F;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



