#ifndef _COMPONENTS_LIB_INTEGRATORTEST_AUTOMATIC_H_
#define _COMPONENTS_LIB_INTEGRATORTEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_IntegratorTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_lib_IntegratorTest
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define tester_VAL components_lib_IntegratorTest.tester
#define tester_REF &(components_lib_IntegratorTest.tester)
#define integrate_inputVal_VAL components_lib_IntegratorTest_CAL_MEM.integrate_inputVal
#define integrate_dtVal_VAL components_lib_IntegratorTest_CAL_MEM.integrate_dtVal
#define outVal_return_VAL components_lib_IntegratorTest_RAM.outVal_return
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_LIB_INTEGRATORTEST_AUTOMATIC_H_ */
