#ifndef _ASD_COMPONENTS_DIFFWHEEL_AUTOMATIC_H_
#define _ASD_COMPONENTS_DIFFWHEEL_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_diffWheel_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 16:43:33
*
* @brief   "components_diffWheel>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_DIFFWHEEL_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............components_diffWheel_Automatic */
#define _components_diffWheel_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_diffWheel_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 components_diffWheel_diffFl;
extern float32 components_diffWheel_diffFr;
extern float32 components_diffWheel_diffRl;
extern float32 components_diffWheel_diffRr;


#endif /* _ASD_COMPONENTS_DIFFWHEEL_AUTOMATIC_H_ */
