#ifndef _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_
#define _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Component_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "components_Component>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_lib_average_Automatic.h"
#include "components_lib_Integrator_Automatic.h"
#include "components_lib_percentCompare_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Component_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_CAL_MEM_SUBSTRUCT {
   struct components_lib_Integrator_Automatic_CAL_MEM_SUBSTRUCT Integrator_instance;
   struct components_lib_Integrator_Automatic_CAL_MEM_SUBSTRUCT Integrator_instance1;
   struct components_lib_Integrator_Automatic_CAL_MEM_SUBSTRUCT Integrator_instance2;
   struct components_lib_Integrator_Automatic_CAL_MEM_SUBSTRUCT Integrator_instance3;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Component_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Component_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_RAM_SUBSTRUCT {
   struct components_lib_Integrator_Automatic_RAM_SUBSTRUCT Integrator_instance;
   struct components_lib_Integrator_Automatic_RAM_SUBSTRUCT Integrator_instance1;
   struct components_lib_Integrator_Automatic_RAM_SUBSTRUCT Integrator_instance2;
   struct components_lib_Integrator_Automatic_RAM_SUBSTRUCT Integrator_instance3;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Component_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_Component_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic {
   struct components_lib_Integrator_Automatic Integrator_instance;
   struct components_lib_Integrator_Automatic Integrator_instance1;
   struct components_lib_Integrator_Automatic Integrator_instance2;
   struct components_lib_Integrator_Automatic Integrator_instance3;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_Component_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............components_Component_Automatic */
#define _components_Component_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_Component_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct components_Component_Automatic_CAL_MEM_SUBSTRUCT components_Component_CAL_MEM;

/* forward declaration of substruct variable 'components_Component_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_Component_Automatic_RAM_SUBSTRUCT components_Component_RAM;

/* forward declaration of component variable 'components_Component' */
/* containing 'ROM' memory class tree */
extern const struct components_Component_Automatic components_Component;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_Component_Automatic
 ******************************************************************************/
extern void components_Component_Automatic_calc (void);



#endif /* _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_ */
