/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_veloCar_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "components_veloCar>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_veloCar_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_veloCar'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................16
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'components_veloCar_vfl' */
float32 components_veloCar_vfl = 0.0F;
/* modelled as 'components_veloCar_vfr' */
float32 components_veloCar_vfr = 0.0F;
/* modelled as 'components_veloCar_vrl' */
float32 components_veloCar_vrl = 0.0F;
/* modelled as 'components_veloCar_vrr' */
float32 components_veloCar_vrr = 0.0F;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



