#ifndef _ASD_COMPONENTS_LIB_DIFFCHECK_AUTOMATIC_H_
#define _ASD_COMPONENTS_LIB_DIFFCHECK_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_diffCheck_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 16:43:33
*
* @brief   "components_lib_diffCheck>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_lib_diffCheck_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_lib_diffCheck_Automatic_CAL_MEM_SUBSTRUCT {
   float32 border;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_lib_diffCheck_Automatic'
 ******************************************************************************/


/* component structure for module COMPONENTS_LIB_DIFFCHECK_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........components_lib_diffCheck_Automatic */
#define _components_lib_diffCheck_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_lib_diffCheck_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct components_lib_diffCheck_Automatic_CAL_MEM_SUBSTRUCT components_lib_diffCheck_CAL_MEM;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_lib_diffCheck_Automatic
 ******************************************************************************/
extern uint8 components_lib_diffCheck_Automatic_calc (/* IN    */ const float32 arg);



#endif /* _ASD_COMPONENTS_LIB_DIFFCHECK_AUTOMATIC_H_ */
