/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_statemaschine_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:39:24
*
* @brief   "components_lib_statemaschine>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_lib_statemaschine_Automatic.h"
#include "PC_PC_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_lib_statemaschine_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_lib_statemaschine'
 * data set:.....................................'COMPONENTS_LIB_STATEMASCHINE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_lib_statemaschine_Automatic_RAM_SUBSTRUCT components_lib_statemaschine_RAM = {
   /* substruct: components_lib_statemaschine_RAM.SoundOutStateMaschine_instance (modeled as:'SoundOutStateMaschine_instance.components_lib_statemaschine') */
   {
      /* struct element:'components_lib_statemaschine_RAM.SoundOutStateMaschine_instance.countLong' (modeled as:'countLong.SoundOutStateMaschine_instance.components_lib_statemaschine') */
      0,
      /* struct element:'components_lib_statemaschine_RAM.SoundOutStateMaschine_instance.countShort' (modeled as:'countShort.SoundOutStateMaschine_instance.components_lib_statemaschine') */
      0,
      /* struct element:'components_lib_statemaschine_RAM.SoundOutStateMaschine_instance.deltaTime' (modeled as:'deltaTime.SoundOutStateMaschine_instance.components_lib_statemaschine') */
      0.0F,
      /* struct element:'components_lib_statemaschine_RAM.SoundOutStateMaschine_instance.time' (modeled as:'time.SoundOutStateMaschine_instance.components_lib_statemaschine') */
      0.0F,
      /* struct element:'components_lib_statemaschine_RAM.SoundOutStateMaschine_instance.lampOn' (modeled as:'lampOn.SoundOutStateMaschine_instance.components_lib_statemaschine') */
      false,
      /* struct element:'components_lib_statemaschine_RAM.SoundOutStateMaschine_instance.sm' (modeled as:'sm.SoundOutStateMaschine_instance.components_lib_statemaschine') */
      0U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_lib_statemaschine_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_lib_statemaschine'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_lib_statemaschine'
 * data set:.....................................'COMPONENTS_LIB_STATEMASCHINE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_lib_statemaschine_Automatic components_lib_statemaschine = {
   /* substruct: components_lib_statemaschine.SoundOutStateMaschine_instance (modeled as:'SoundOutStateMaschine_instance.components_lib_statemaschine') */
   {
      /* type descriptor pointer 'components_SoundOutStateMaschine_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_lib_statemaschine_RAM.SoundOutStateMaschine_instance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_lib_statemaschine'
 ******************************************************************************/





#define dT_VAL (ASD_DT_SCALED)
#define SoundOutStateMaschine_instance_REF (&(components_lib_statemaschine.SoundOutStateMaschine_instance))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_lib_statemaschine_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_lib_statemaschine_Automatic_calc (void)
{
   components_SoundOutStateMaschine_Automatic_soundOutStateMaschineStatemachineTrigger(SoundOutStateMaschine_instance_REF);
   components_lib_statemaschine_RAM.SoundOutStateMaschine_instance.deltaTime = dT_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_lib_statemaschine_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



