#ifndef _ASD_COMPONENTS_DISTANCECAR_AUTOMATIC_H_
#define _ASD_COMPONENTS_DISTANCECAR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_distanceCar_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "components_distanceCar>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_DISTANCECAR_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........components_distanceCar_Automatic */
#define _components_distanceCar_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_distanceCar_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 components_distanceCar_avgDistanceCar;
extern float32 components_distanceCar_sfl;
extern float32 components_distanceCar_sfr;
extern float32 components_distanceCar_srl;
extern float32 components_distanceCar_srr;


#endif /* _ASD_COMPONENTS_DISTANCECAR_AUTOMATIC_H_ */
