#ifndef _ASD_COMPONENTS_LIB_AVERAGE_AUTOMATIC_H_
#define _ASD_COMPONENTS_LIB_AVERAGE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_average_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 16:43:33
*
* @brief   "components_lib_average>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for class COMPONENTS_LIB_AVERAGE_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........components_lib_average_Automatic */
#define _components_lib_average_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_lib_average_Automatic
 ******************************************************************************/
extern float32 components_lib_average_Automatic_calc (
   /* IN    */ const float32 arg,
   /* IN    */ const float32 arg_2,
   /* IN    */ const float32 arg_3,
   /* IN    */ const float32 arg_4
   );



#endif /* _ASD_COMPONENTS_LIB_AVERAGE_AUTOMATIC_H_ */
