/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_distanceCar_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "components_distanceCar>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_distanceCar_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_distanceCar'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................20
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'components_distanceCar_avgDistanceCar' */
float32 components_distanceCar_avgDistanceCar = 0.0F;
/* modelled as 'components_distanceCar_sfl' */
float32 components_distanceCar_sfl = 0.0F;
/* modelled as 'components_distanceCar_sfr' */
float32 components_distanceCar_sfr = 0.0F;
/* modelled as 'components_distanceCar_srl' */
float32 components_distanceCar_srl = 0.0F;
/* modelled as 'components_distanceCar_srr' */
float32 components_distanceCar_srr = 0.0F;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



