#ifndef _COMPONENTS_LIB_INTEGRATOR_AUTOMATIC_H_
#define _COMPONENTS_LIB_INTEGRATOR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_Integrator_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_lib_Integrator
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define memory_VAL self->components_lib_Integrator_Automatic_RAM->memory
#define kI_VAL self->components_lib_Integrator_Automatic_CAL_MEM->kI
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_LIB_INTEGRATOR_AUTOMATIC_H_ */
