#ifndef _ASD_COMPONENTS_PRESSUREERROR_AUTOMATIC_H_
#define _ASD_COMPONENTS_PRESSUREERROR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_pressureError_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "components_pressureError>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_PRESSUREERROR_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........components_pressureError_Automatic */
#define _components_pressureError_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_pressureError_Automatic
 ******************************************************************************/


/* declaration of messages */
extern uint8 components_pressureError_err;
extern uint8 components_pressureError_errFl;
extern uint8 components_pressureError_errFr;
extern uint8 components_pressureError_errRl;
extern uint8 components_pressureError_errRr;


#endif /* _ASD_COMPONENTS_PRESSUREERROR_AUTOMATIC_H_ */
