#ifndef _ASD_COMPONENTS_VELOCAR_AUTOMATIC_H_
#define _ASD_COMPONENTS_VELOCAR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_veloCar_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "components_veloCar>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_VELOCAR_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...............components_veloCar_Automatic */
#define _components_veloCar_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_veloCar_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 components_veloCar_vfl;
extern float32 components_veloCar_vfr;
extern float32 components_veloCar_vrl;
extern float32 components_veloCar_vrr;


#endif /* _ASD_COMPONENTS_VELOCAR_AUTOMATIC_H_ */
