#ifndef _COMPONENTS_SOUNDOUTSTATEMASCHINE_AUTOMATIC_H_
#define _COMPONENTS_SOUNDOUTSTATEMASCHINE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_SoundOutStateMaschine_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_SoundOutStateMaschine
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define deltaTime_VAL self->components_SoundOutStateMaschine_Automatic_RAM->deltaTime
#define time_VAL self->components_SoundOutStateMaschine_Automatic_RAM->time
#define countShort_VAL self->components_SoundOutStateMaschine_Automatic_RAM->countShort
#define countLong_VAL self->components_SoundOutStateMaschine_Automatic_RAM->countLong
#define lampOn_VAL self->components_SoundOutStateMaschine_Automatic_RAM->lampOn
#define sm_VAL self->components_SoundOutStateMaschine_Automatic_RAM->sm
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_SOUNDOUTSTATEMASCHINE_AUTOMATIC_H_ */
