/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_NoiseGenerator_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 14:54:09
*
* @brief   "components_lib_NoiseGenerator>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_lib_NoiseGenerator_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define mem_VAL (self->components_lib_NoiseGenerator_Automatic_RAM->mem)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_lib_NoiseGenerator_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_lib_NoiseGenerator_Automatic_calc (
               const struct components_lib_NoiseGenerator_Automatic * self,
   /* IN    */ const uint16                                           argA,
   /* IN    */ const uint16                                           argC,
   /* IN    */ const uint16                                           argM,
   /* IN    */ const float32                                          scaleGain
   )
{
   /* temp. variables */
   uint32 _t1uint32;

   _t1uint32 = (((uint32)mem_VAL * argA) + argC) % argM;
   mem_VAL = (uint16)(((_t1uint32 > 1U) ? _t1uint32 : 1U));
   return (float32)mem_VAL * scaleGain;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_lib_NoiseGenerator_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



