#ifndef _ASD_COMPONENTS_SOUNDOUTSTATEMASCHINE_AUTOMATIC_H_
#define _ASD_COMPONENTS_SOUNDOUTSTATEMASCHINE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_SoundOutStateMaschine_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 16:43:33
*
* @brief   "components_SoundOutStateMaschine>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_SoundOutStateMaschine_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_SoundOutStateMaschine_Automatic_RAM_SUBSTRUCT {
   sint32 countLong;
   sint32 countShort;
   float32 deltaTime;
   float32 time;
   uint8 lampOn;
   uint8 sm;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_SoundOutStateMaschine_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_SoundOutStateMaschine_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_SoundOutStateMaschine_Automatic {
   struct components_SoundOutStateMaschine_Automatic_RAM_SUBSTRUCT * components_SoundOutStateMaschine_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_SoundOutStateMaschine_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .components_SoundOutStateMaschine_Automatic */
#define _components_SoundOutStateMaschine_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_SoundOutStateMaschine_Automatic
 ******************************************************************************/
uint8 components_SoundOutStateMaschine_Automatic_esdl_getState ( const struct components_SoundOutStateMaschine_Automatic * self);
extern void components_SoundOutStateMaschine_Automatic_soundOutStateMaschineStatemachineTrigger ( const struct components_SoundOutStateMaschine_Automatic * self);



#endif /* _ASD_COMPONENTS_SOUNDOUTSTATEMASCHINE_AUTOMATIC_H_ */
