/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_average_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    08.03.2019 17:48:32
*
* @brief   "components_lib_average>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_lib_average_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a single instance class
 ******************************************************************************/


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'test'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_lib_average_Automatic_avgOn4Inputs'
 * ----------------------------------------------------------------------------
 * model name:...................................'avgOn4Inputs'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_lib_average_Automatic_avgOn4Inputs (
   /* IN    */ const float32 arg1,
   /* IN    */ const float32 arg2,
   /* IN    */ const float32 arg3,
   /* IN    */ const float32 arg4
   )
{
   return (arg1 + arg2 + arg3 + arg4) * 0.25F;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_lib_average_Automatic_avgOn4Inputs'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



