/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Component_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "components_Component>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Component_Automatic.h"
#include "components_diffWheel_Automatic.h"
#include "components_distanceCar_Automatic.h"
#include "components_lib_diffCheck_Automatic.h"
#include "components_pressureError_Automatic.h"
#include "components_veloCar_Automatic.h"
#include "PC_PC_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_CAL_MEM_SUBSTRUCT components_Component_CAL_MEM = {
   /* substruct: components_Component_CAL_MEM.Integrator_instance (modeled as:'Integrator_instance.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.Integrator_instance.kI' (modeled as:'kI.Integrator_instance.components_Component') */
      4.0F
   },
   /* substruct: components_Component_CAL_MEM.Integrator_instance1 (modeled as:'Integrator_instance1.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.Integrator_instance1.kI' (modeled as:'kI.Integrator_instance1.components_Component') */
      4.0F
   },
   /* substruct: components_Component_CAL_MEM.Integrator_instance2 (modeled as:'Integrator_instance2.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.Integrator_instance2.kI' (modeled as:'kI.Integrator_instance2.components_Component') */
      4.0F
   },
   /* substruct: components_Component_CAL_MEM.Integrator_instance3 (modeled as:'Integrator_instance3.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.Integrator_instance3.kI' (modeled as:'kI.Integrator_instance3.components_Component') */
      4.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_RAM_SUBSTRUCT components_Component_RAM = {
   /* substruct: components_Component_RAM.Integrator_instance (modeled as:'Integrator_instance.components_Component') */
   {
      /* struct element:'components_Component_RAM.Integrator_instance.memory' (modeled as:'memory.Integrator_instance.components_Component') */
      0.0F
   },
   /* substruct: components_Component_RAM.Integrator_instance1 (modeled as:'Integrator_instance1.components_Component') */
   {
      /* struct element:'components_Component_RAM.Integrator_instance1.memory' (modeled as:'memory.Integrator_instance1.components_Component') */
      0.0F
   },
   /* substruct: components_Component_RAM.Integrator_instance2 (modeled as:'Integrator_instance2.components_Component') */
   {
      /* struct element:'components_Component_RAM.Integrator_instance2.memory' (modeled as:'memory.Integrator_instance2.components_Component') */
      0.0F
   },
   /* substruct: components_Component_RAM.Integrator_instance3 (modeled as:'Integrator_instance3.components_Component') */
   {
      /* struct element:'components_Component_RAM.Integrator_instance3.memory' (modeled as:'memory.Integrator_instance3.components_Component') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_Component'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_Component_Automatic components_Component = {
   /* substruct: components_Component.Integrator_instance (modeled as:'Integrator_instance.components_Component') */
   {
      /* type descriptor pointer 'components_lib_Integrator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.Integrator_instance,
      /* type descriptor pointer 'components_lib_Integrator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.Integrator_instance
   },
   /* substruct: components_Component.Integrator_instance1 (modeled as:'Integrator_instance1.components_Component') */
   {
      /* type descriptor pointer 'components_lib_Integrator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.Integrator_instance1,
      /* type descriptor pointer 'components_lib_Integrator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.Integrator_instance1
   },
   /* substruct: components_Component.Integrator_instance2 (modeled as:'Integrator_instance2.components_Component') */
   {
      /* type descriptor pointer 'components_lib_Integrator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.Integrator_instance2,
      /* type descriptor pointer 'components_lib_Integrator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.Integrator_instance2
   },
   /* substruct: components_Component.Integrator_instance3 (modeled as:'Integrator_instance3.components_Component') */
   {
      /* type descriptor pointer 'components_lib_Integrator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.Integrator_instance3,
      /* type descriptor pointer 'components_lib_Integrator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.Integrator_instance3
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_Component'
 ******************************************************************************/





#define dT_VAL (ASD_DT_SCALED)
#define Integrator_instance_REF (&(components_Component.Integrator_instance))
#define Integrator_instance1_REF (&(components_Component.Integrator_instance1))
#define Integrator_instance2_REF (&(components_Component.Integrator_instance2))
#define Integrator_instance3_REF (&(components_Component.Integrator_instance3))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_Component_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void components_Component_Automatic_calc (void)
{
   /* define local message copies */
   float32 components_diffWheel_diffFl__components_Component_Automatic_calc;
   float32 components_diffWheel_diffFr__components_Component_Automatic_calc;
   float32 components_diffWheel_diffRl__components_Component_Automatic_calc;
   float32 components_diffWheel_diffRr__components_Component_Automatic_calc;
   float32 components_distanceCar_avgDistanceCar__components_Component_Automatic_calc;
   float32 components_distanceCar_sfl__components_Component_Automatic_calc;
   float32 components_distanceCar_sfr__components_Component_Automatic_calc;
   float32 components_distanceCar_srl__components_Component_Automatic_calc;
   float32 components_distanceCar_srr__components_Component_Automatic_calc;
   uint8 components_pressureError_err__components_Component_Automatic_calc;
   uint8 components_pressureError_errFl__components_Component_Automatic_calc;
   uint8 components_pressureError_errFr__components_Component_Automatic_calc;
   uint8 components_pressureError_errRl__components_Component_Automatic_calc;
   uint8 components_pressureError_errRr__components_Component_Automatic_calc;
   float32 components_veloCar_vfl__components_Component_Automatic_calc;
   float32 components_veloCar_vfr__components_Component_Automatic_calc;
   float32 components_veloCar_vrl__components_Component_Automatic_calc;
   float32 components_veloCar_vrr__components_Component_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      components_diffWheel_diffFl__components_Component_Automatic_calc = components_diffWheel_diffFl;
      components_diffWheel_diffFr__components_Component_Automatic_calc = components_diffWheel_diffFr;
      components_diffWheel_diffRl__components_Component_Automatic_calc = components_diffWheel_diffRl;
      components_diffWheel_diffRr__components_Component_Automatic_calc = components_diffWheel_diffRr;
      components_distanceCar_avgDistanceCar__components_Component_Automatic_calc = components_distanceCar_avgDistanceCar;
      components_distanceCar_sfl__components_Component_Automatic_calc = components_distanceCar_sfl;
      components_distanceCar_sfr__components_Component_Automatic_calc = components_distanceCar_sfr;
      components_distanceCar_srl__components_Component_Automatic_calc = components_distanceCar_srl;
      components_distanceCar_srr__components_Component_Automatic_calc = components_distanceCar_srr;
      components_pressureError_errFl__components_Component_Automatic_calc = components_pressureError_errFl;
      components_pressureError_errFr__components_Component_Automatic_calc = components_pressureError_errFr;
      components_pressureError_errRl__components_Component_Automatic_calc = components_pressureError_errRl;
      components_pressureError_errRr__components_Component_Automatic_calc = components_pressureError_errRr;
      components_pressureError_err__components_Component_Automatic_calc = components_pressureError_err;
      components_veloCar_vfl__components_Component_Automatic_calc = components_veloCar_vfl;
      components_veloCar_vfr__components_Component_Automatic_calc = components_veloCar_vfr;
      components_veloCar_vrl__components_Component_Automatic_calc = components_veloCar_vrl;
      components_veloCar_vrr__components_Component_Automatic_calc = components_veloCar_vrr;
      EnableAllInterrupts();
   }
   components_lib_Integrator_Automatic_integrate(Integrator_instance_REF, components_veloCar_vfl__components_Component_Automatic_calc, dT_VAL);
   components_distanceCar_sfl__components_Component_Automatic_calc
      = components_lib_Integrator_Automatic_outVal(Integrator_instance_REF);
   components_distanceCar_sfr__components_Component_Automatic_calc
      = components_lib_Integrator_Automatic_outVal(Integrator_instance1_REF);
   components_distanceCar_srl__components_Component_Automatic_calc
      = components_lib_Integrator_Automatic_outVal(Integrator_instance2_REF);
   components_distanceCar_srr__components_Component_Automatic_calc
      = components_lib_Integrator_Automatic_outVal(Integrator_instance3_REF);
   components_lib_Integrator_Automatic_integrate(Integrator_instance1_REF, components_veloCar_vfr__components_Component_Automatic_calc, dT_VAL);
   components_lib_Integrator_Automatic_integrate(Integrator_instance2_REF, components_veloCar_vrl__components_Component_Automatic_calc, dT_VAL);
   components_lib_Integrator_Automatic_integrate(Integrator_instance3_REF, components_veloCar_vrr__components_Component_Automatic_calc, dT_VAL);
   components_distanceCar_avgDistanceCar__components_Component_Automatic_calc
      = components_lib_average_Automatic_calc(components_distanceCar_sfl__components_Component_Automatic_calc, components_distanceCar_sfr__components_Component_Automatic_calc, components_distanceCar_srl__components_Component_Automatic_calc, components_distanceCar_srr__components_Component_Automatic_calc);
   components_diffWheel_diffFl__components_Component_Automatic_calc
      = components_lib_percentCompare_Automatic_calc(components_distanceCar_sfl__components_Component_Automatic_calc, components_distanceCar_avgDistanceCar__components_Component_Automatic_calc);
   components_diffWheel_diffFr__components_Component_Automatic_calc
      = components_lib_percentCompare_Automatic_calc(components_distanceCar_sfr__components_Component_Automatic_calc, components_distanceCar_avgDistanceCar__components_Component_Automatic_calc);
   components_diffWheel_diffRl__components_Component_Automatic_calc
      = components_lib_percentCompare_Automatic_calc(components_distanceCar_srl__components_Component_Automatic_calc, components_distanceCar_avgDistanceCar__components_Component_Automatic_calc);
   components_diffWheel_diffRr__components_Component_Automatic_calc
      = components_lib_percentCompare_Automatic_calc(components_distanceCar_srr__components_Component_Automatic_calc, components_distanceCar_avgDistanceCar__components_Component_Automatic_calc);
   components_pressureError_errFl__components_Component_Automatic_calc
      = components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFl__components_Component_Automatic_calc);
   components_pressureError_errFr__components_Component_Automatic_calc
      = components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFr__components_Component_Automatic_calc);
   components_pressureError_errRl__components_Component_Automatic_calc
      = components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRl__components_Component_Automatic_calc);
   components_pressureError_errRr__components_Component_Automatic_calc
      = components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRr__components_Component_Automatic_calc);
   components_pressureError_err__components_Component_Automatic_calc
      = (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFl__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFr__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRl__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRr__components_Component_Automatic_calc));
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      components_diffWheel_diffFl = components_diffWheel_diffFl__components_Component_Automatic_calc;
      components_diffWheel_diffFr = components_diffWheel_diffFr__components_Component_Automatic_calc;
      components_diffWheel_diffRl = components_diffWheel_diffRl__components_Component_Automatic_calc;
      components_diffWheel_diffRr = components_diffWheel_diffRr__components_Component_Automatic_calc;
      components_distanceCar_avgDistanceCar = components_distanceCar_avgDistanceCar__components_Component_Automatic_calc;
      components_distanceCar_sfl = components_distanceCar_sfl__components_Component_Automatic_calc;
      components_distanceCar_sfr = components_distanceCar_sfr__components_Component_Automatic_calc;
      components_distanceCar_srl = components_distanceCar_srl__components_Component_Automatic_calc;
      components_distanceCar_srr = components_distanceCar_srr__components_Component_Automatic_calc;
      components_pressureError_err = components_pressureError_err__components_Component_Automatic_calc;
      components_pressureError_errFl = components_pressureError_errFl__components_Component_Automatic_calc;
      components_pressureError_errFr = components_pressureError_errFr__components_Component_Automatic_calc;
      components_pressureError_errRl = components_pressureError_errRl__components_Component_Automatic_calc;
      components_pressureError_errRr = components_pressureError_errRr__components_Component_Automatic_calc;
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_Component_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



