/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Component_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 16:43:33
*
* @brief   "components_Component>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Component_Automatic.h"
#include "components_diffWheel_Automatic.h"
#include "components_distanceCar_Automatic.h"
#include "components_lib_diffCheck_Automatic.h"
#include "components_pressureError_Automatic.h"
#include "components_veloCar_Automatic.h"
#include "PC_PC_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_CAL_MEM_SUBSTRUCT components_Component_CAL_MEM = {
   /* struct element:'components_Component_CAL_MEM.gain' (modeled as:'gain.components_Component') */
   0.0F,
   /* struct element:'components_Component_CAL_MEM.vflA' (modeled as:'vflA.components_Component') */
   0,
   /* struct element:'components_Component_CAL_MEM.vflC' (modeled as:'vflC.components_Component') */
   0,
   /* struct element:'components_Component_CAL_MEM.vflM' (modeled as:'vflM.components_Component') */
   0,
   /* substruct: components_Component_CAL_MEM.Integrator_instance (modeled as:'Integrator_instance.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.Integrator_instance.kI' (modeled as:'kI.Integrator_instance.components_Component') */
      1.0F
   },
   /* substruct: components_Component_CAL_MEM.Integrator_instance1 (modeled as:'Integrator_instance1.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.Integrator_instance1.kI' (modeled as:'kI.Integrator_instance1.components_Component') */
      1.0F
   },
   /* substruct: components_Component_CAL_MEM.Integrator_instance2 (modeled as:'Integrator_instance2.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.Integrator_instance2.kI' (modeled as:'kI.Integrator_instance2.components_Component') */
      1.0F
   },
   /* substruct: components_Component_CAL_MEM.Integrator_instance3 (modeled as:'Integrator_instance3.components_Component') */
   {
      /* struct element:'components_Component_CAL_MEM.Integrator_instance3.kI' (modeled as:'kI.Integrator_instance3.components_Component') */
      1.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Component_Automatic_RAM_SUBSTRUCT components_Component_RAM = {
   /* substruct: components_Component_RAM.Integrator_instance (modeled as:'Integrator_instance.components_Component') */
   {
      /* struct element:'components_Component_RAM.Integrator_instance.memory' (modeled as:'memory.Integrator_instance.components_Component') */
      0.0F
   },
   /* substruct: components_Component_RAM.Integrator_instance1 (modeled as:'Integrator_instance1.components_Component') */
   {
      /* struct element:'components_Component_RAM.Integrator_instance1.memory' (modeled as:'memory.Integrator_instance1.components_Component') */
      0.0F
   },
   /* substruct: components_Component_RAM.Integrator_instance2 (modeled as:'Integrator_instance2.components_Component') */
   {
      /* struct element:'components_Component_RAM.Integrator_instance2.memory' (modeled as:'memory.Integrator_instance2.components_Component') */
      0.0F
   },
   /* substruct: components_Component_RAM.Integrator_instance3 (modeled as:'Integrator_instance3.components_Component') */
   {
      /* struct element:'components_Component_RAM.Integrator_instance3.memory' (modeled as:'memory.Integrator_instance3.components_Component') */
      0.0F
   },
   /* substruct: components_Component_RAM.NoiseGenerator_instance (modeled as:'NoiseGenerator_instance.components_Component') */
   {
      /* struct element:'components_Component_RAM.NoiseGenerator_instance.mem' (modeled as:'mem.NoiseGenerator_instance.components_Component') */
      1U
   },
   /* substruct: components_Component_RAM.NoiseGenerator_instance_2 (modeled as:'NoiseGenerator_instance_2.components_Component') */
   {
      /* struct element:'components_Component_RAM.NoiseGenerator_instance_2.mem' (modeled as:'mem.NoiseGenerator_instance_2.components_Component') */
      1U
   },
   /* substruct: components_Component_RAM.NoiseGenerator_instance_3 (modeled as:'NoiseGenerator_instance_3.components_Component') */
   {
      /* struct element:'components_Component_RAM.NoiseGenerator_instance_3.mem' (modeled as:'mem.NoiseGenerator_instance_3.components_Component') */
      1U
   },
   /* substruct: components_Component_RAM.NoiseGenerator_instance_4 (modeled as:'NoiseGenerator_instance_4.components_Component') */
   {
      /* struct element:'components_Component_RAM.NoiseGenerator_instance_4.mem' (modeled as:'mem.NoiseGenerator_instance_4.components_Component') */
      1U
   },
   /* substruct: components_Component_RAM.SoundOutStateMaschine_instance (modeled as:'SoundOutStateMaschine_instance.components_Component') */
   {
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance.countLong' (modeled as:'countLong.SoundOutStateMaschine_instance.components_Component') */
      0,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance.countShort' (modeled as:'countShort.SoundOutStateMaschine_instance.components_Component') */
      0,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance.deltaTime' (modeled as:'deltaTime.SoundOutStateMaschine_instance.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance.time' (modeled as:'time.SoundOutStateMaschine_instance.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance.lampOn' (modeled as:'lampOn.SoundOutStateMaschine_instance.components_Component') */
      false,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance.sm' (modeled as:'sm.SoundOutStateMaschine_instance.components_Component') */
      0U
   },
   /* substruct: components_Component_RAM.SoundOutStateMaschine_instance_2 (modeled as:'SoundOutStateMaschine_instance_2.components_Component') */
   {
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance_2.countLong' (modeled as:'countLong.SoundOutStateMaschine_instance_2.components_Component') */
      0,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance_2.countShort' (modeled as:'countShort.SoundOutStateMaschine_instance_2.components_Component') */
      0,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance_2.deltaTime' (modeled as:'deltaTime.SoundOutStateMaschine_instance_2.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance_2.time' (modeled as:'time.SoundOutStateMaschine_instance_2.components_Component') */
      0.0F,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance_2.lampOn' (modeled as:'lampOn.SoundOutStateMaschine_instance_2.components_Component') */
      false,
      /* struct element:'components_Component_RAM.SoundOutStateMaschine_instance_2.sm' (modeled as:'sm.SoundOutStateMaschine_instance_2.components_Component') */
      0U
   },
   /* substruct: components_Component_RAM.TirePressureProject_instance (modeled as:'TirePressureProject_instance.components_Component') */
   {
      /* struct element:'components_Component_RAM.TirePressureProject_instance.mem' (modeled as:'mem.TirePressureProject_instance.components_Component') */
      1U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Component_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_Component'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Component'
 * data set:.....................................'COMPONENTS_COMPONENT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_Component_Automatic components_Component = {
   /* substruct: components_Component.Integrator_instance (modeled as:'Integrator_instance.components_Component') */
   {
      /* type descriptor pointer 'components_lib_Integrator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.Integrator_instance,
      /* type descriptor pointer 'components_lib_Integrator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.Integrator_instance
   },
   /* substruct: components_Component.Integrator_instance1 (modeled as:'Integrator_instance1.components_Component') */
   {
      /* type descriptor pointer 'components_lib_Integrator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.Integrator_instance1,
      /* type descriptor pointer 'components_lib_Integrator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.Integrator_instance1
   },
   /* substruct: components_Component.Integrator_instance2 (modeled as:'Integrator_instance2.components_Component') */
   {
      /* type descriptor pointer 'components_lib_Integrator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.Integrator_instance2,
      /* type descriptor pointer 'components_lib_Integrator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.Integrator_instance2
   },
   /* substruct: components_Component.Integrator_instance3 (modeled as:'Integrator_instance3.components_Component') */
   {
      /* type descriptor pointer 'components_lib_Integrator_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Component_CAL_MEM.Integrator_instance3,
      /* type descriptor pointer 'components_lib_Integrator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.Integrator_instance3
   },
   /* substruct: components_Component.NoiseGenerator_instance (modeled as:'NoiseGenerator_instance.components_Component') */
   {
      /* type descriptor pointer 'components_lib_NoiseGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.NoiseGenerator_instance
   },
   /* substruct: components_Component.NoiseGenerator_instance_2 (modeled as:'NoiseGenerator_instance_2.components_Component') */
   {
      /* type descriptor pointer 'components_lib_NoiseGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.NoiseGenerator_instance_2
   },
   /* substruct: components_Component.NoiseGenerator_instance_3 (modeled as:'NoiseGenerator_instance_3.components_Component') */
   {
      /* type descriptor pointer 'components_lib_NoiseGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.NoiseGenerator_instance_3
   },
   /* substruct: components_Component.NoiseGenerator_instance_4 (modeled as:'NoiseGenerator_instance_4.components_Component') */
   {
      /* type descriptor pointer 'components_lib_NoiseGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.NoiseGenerator_instance_4
   },
   /* substruct: components_Component.SoundOutStateMaschine_instance (modeled as:'SoundOutStateMaschine_instance.components_Component') */
   {
      /* type descriptor pointer 'components_SoundOutStateMaschine_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.SoundOutStateMaschine_instance
   },
   /* substruct: components_Component.SoundOutStateMaschine_instance_2 (modeled as:'SoundOutStateMaschine_instance_2.components_Component') */
   {
      /* type descriptor pointer 'components_SoundOutStateMaschine_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.SoundOutStateMaschine_instance_2
   },
   /* substruct: components_Component.TirePressureProject_instance (modeled as:'TirePressureProject_instance.components_Component') */
   {
      /* type descriptor pointer 'components_lib_NoiseGenerator_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Component_RAM.TirePressureProject_instance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_Component'
 ******************************************************************************/





/******************************************************************************
 * BEGIN: DEFINITION OF VARIABLE 'components_Component_reset'
 * ---------------------------------------------------------------------------*/
uint8 components_Component_reset = false;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF VARIABLE 'components_Component_reset'
 ******************************************************************************/


#define dT_VAL (ASD_DT_SCALED)
#define Integrator_instance_REF (&(components_Component.Integrator_instance))
#define Integrator_instance1_REF (&(components_Component.Integrator_instance1))
#define Integrator_instance2_REF (&(components_Component.Integrator_instance2))
#define Integrator_instance3_REF (&(components_Component.Integrator_instance3))
#define NoiseGenerator_instance_2_REF (&(components_Component.NoiseGenerator_instance_2))
#define NoiseGenerator_instance_3_REF (&(components_Component.NoiseGenerator_instance_3))
#define NoiseGenerator_instance_4_REF (&(components_Component.NoiseGenerator_instance_4))
#define NoiseGenerator_instance_REF (&(components_Component.NoiseGenerator_instance))
#define SoundOutStateMaschine_instance_2_REF (&(components_Component.SoundOutStateMaschine_instance_2))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_Component_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void components_Component_Automatic_calc (void)
{
   /* define local message copies */
   float32 components_diffWheel_diffFl__components_Component_Automatic_calc;
   float32 components_diffWheel_diffFr__components_Component_Automatic_calc;
   float32 components_diffWheel_diffRl__components_Component_Automatic_calc;
   float32 components_diffWheel_diffRr__components_Component_Automatic_calc;
   float32 components_distanceCar_avgDistanceCar__components_Component_Automatic_calc;
   float32 components_distanceCar_sfl__components_Component_Automatic_calc;
   float32 components_distanceCar_sfr__components_Component_Automatic_calc;
   float32 components_distanceCar_srl__components_Component_Automatic_calc;
   float32 components_distanceCar_srr__components_Component_Automatic_calc;
   uint8 components_pressureError_err__components_Component_Automatic_calc;
   uint8 components_pressureError_errFl__components_Component_Automatic_calc;
   uint8 components_pressureError_errFr__components_Component_Automatic_calc;
   uint8 components_pressureError_errRl__components_Component_Automatic_calc;
   uint8 components_pressureError_errRr__components_Component_Automatic_calc;
   float32 components_veloCar_vfl__components_Component_Automatic_calc;
   float32 components_veloCar_vfr__components_Component_Automatic_calc;
   float32 components_veloCar_vrl__components_Component_Automatic_calc;
   float32 components_veloCar_vrr__components_Component_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      components_diffWheel_diffFl__components_Component_Automatic_calc = components_diffWheel_diffFl;
      components_diffWheel_diffFr__components_Component_Automatic_calc = components_diffWheel_diffFr;
      components_diffWheel_diffRl__components_Component_Automatic_calc = components_diffWheel_diffRl;
      components_diffWheel_diffRr__components_Component_Automatic_calc = components_diffWheel_diffRr;
      components_distanceCar_avgDistanceCar__components_Component_Automatic_calc = components_distanceCar_avgDistanceCar;
      components_distanceCar_sfl__components_Component_Automatic_calc = components_distanceCar_sfl;
      components_distanceCar_sfr__components_Component_Automatic_calc = components_distanceCar_sfr;
      components_distanceCar_srl__components_Component_Automatic_calc = components_distanceCar_srl;
      components_distanceCar_srr__components_Component_Automatic_calc = components_distanceCar_srr;
      components_pressureError_errFl__components_Component_Automatic_calc = components_pressureError_errFl;
      components_pressureError_errFr__components_Component_Automatic_calc = components_pressureError_errFr;
      components_pressureError_errRl__components_Component_Automatic_calc = components_pressureError_errRl;
      components_pressureError_errRr__components_Component_Automatic_calc = components_pressureError_errRr;
      components_pressureError_err__components_Component_Automatic_calc = components_pressureError_err;
      components_veloCar_vfl__components_Component_Automatic_calc = components_veloCar_vfl;
      components_veloCar_vfr__components_Component_Automatic_calc = components_veloCar_vfr;
      components_veloCar_vrl__components_Component_Automatic_calc = components_veloCar_vrl;
      components_veloCar_vrr__components_Component_Automatic_calc = components_veloCar_vrr;
      EnableAllInterrupts();
   }
   components_distanceCar_sfl__components_Component_Automatic_calc
      = components_lib_Integrator_Automatic_outVal(Integrator_instance_REF);
   components_distanceCar_sfr__components_Component_Automatic_calc
      = components_lib_Integrator_Automatic_outVal(Integrator_instance1_REF);
   components_distanceCar_srl__components_Component_Automatic_calc
      = components_lib_Integrator_Automatic_outVal(Integrator_instance2_REF);
   components_distanceCar_srr__components_Component_Automatic_calc
      = components_lib_Integrator_Automatic_outVal(Integrator_instance3_REF);
   components_distanceCar_avgDistanceCar__components_Component_Automatic_calc
      = components_lib_average_Automatic_calc(components_distanceCar_sfl__components_Component_Automatic_calc, components_distanceCar_sfr__components_Component_Automatic_calc, components_distanceCar_srl__components_Component_Automatic_calc, components_distanceCar_srr__components_Component_Automatic_calc);
   components_diffWheel_diffFl__components_Component_Automatic_calc
      = components_lib_percentCompare_Automatic_calc(components_distanceCar_sfl__components_Component_Automatic_calc, components_distanceCar_avgDistanceCar__components_Component_Automatic_calc);
   components_diffWheel_diffFr__components_Component_Automatic_calc
      = components_lib_percentCompare_Automatic_calc(components_distanceCar_sfr__components_Component_Automatic_calc, components_distanceCar_avgDistanceCar__components_Component_Automatic_calc);
   components_diffWheel_diffRl__components_Component_Automatic_calc
      = components_lib_percentCompare_Automatic_calc(components_distanceCar_srl__components_Component_Automatic_calc, components_distanceCar_avgDistanceCar__components_Component_Automatic_calc);
   components_diffWheel_diffRr__components_Component_Automatic_calc
      = components_lib_percentCompare_Automatic_calc(components_distanceCar_srr__components_Component_Automatic_calc, components_distanceCar_avgDistanceCar__components_Component_Automatic_calc);
   components_pressureError_errFl__components_Component_Automatic_calc
      = components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFl__components_Component_Automatic_calc);
   components_pressureError_errFr__components_Component_Automatic_calc
      = components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFr__components_Component_Automatic_calc);
   components_pressureError_errRl__components_Component_Automatic_calc
      = components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRl__components_Component_Automatic_calc);
   components_pressureError_errRr__components_Component_Automatic_calc
      = components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRr__components_Component_Automatic_calc);
   components_pressureError_err__components_Component_Automatic_calc
      = (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFl__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFr__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRl__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRr__components_Component_Automatic_calc));
   components_lib_Integrator_Automatic_integrate(Integrator_instance_REF, components_lib_NoiseGenerator_Automatic_calc(NoiseGenerator_instance_REF, 2U, 7U, 17U, 0.01F) + components_veloCar_vfl__components_Component_Automatic_calc, dT_VAL);
   components_lib_Integrator_Automatic_integrate(Integrator_instance1_REF, components_lib_NoiseGenerator_Automatic_calc(NoiseGenerator_instance_2_REF, 3U, 9U, 17U, 0.01F) + components_veloCar_vfr__components_Component_Automatic_calc, dT_VAL);
   components_lib_Integrator_Automatic_integrate(Integrator_instance2_REF, components_lib_NoiseGenerator_Automatic_calc(NoiseGenerator_instance_3_REF, 2U, 7U, 17U, 0.01F) + components_veloCar_vrl__components_Component_Automatic_calc, dT_VAL);
   components_lib_Integrator_Automatic_integrate(Integrator_instance3_REF, components_lib_NoiseGenerator_Automatic_calc(NoiseGenerator_instance_4_REF, 4U, 11U, 17U, 0.01F) + components_veloCar_vrr__components_Component_Automatic_calc, dT_VAL);
   if ((components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFl__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffFr__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRl__components_Component_Automatic_calc))
      || (components_lib_diffCheck_Automatic_calc(components_diffWheel_diffRr__components_Component_Automatic_calc)))
   {
      components_SoundOutStateMaschine_Automatic_soundOutStateMaschineStatemachineTrigger(SoundOutStateMaschine_instance_2_REF);
   }
   else
   {
      components_Component_RAM.SoundOutStateMaschine_instance_2.lampOn = false;
   } /* end if */
   components_Component_RAM.SoundOutStateMaschine_instance_2.deltaTime = dT_VAL;
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      components_diffWheel_diffFl = components_diffWheel_diffFl__components_Component_Automatic_calc;
      components_diffWheel_diffFr = components_diffWheel_diffFr__components_Component_Automatic_calc;
      components_diffWheel_diffRl = components_diffWheel_diffRl__components_Component_Automatic_calc;
      components_diffWheel_diffRr = components_diffWheel_diffRr__components_Component_Automatic_calc;
      components_distanceCar_avgDistanceCar = components_distanceCar_avgDistanceCar__components_Component_Automatic_calc;
      components_distanceCar_sfl = components_distanceCar_sfl__components_Component_Automatic_calc;
      components_distanceCar_sfr = components_distanceCar_sfr__components_Component_Automatic_calc;
      components_distanceCar_srl = components_distanceCar_srl__components_Component_Automatic_calc;
      components_distanceCar_srr = components_distanceCar_srr__components_Component_Automatic_calc;
      components_pressureError_err = components_pressureError_err__components_Component_Automatic_calc;
      components_pressureError_errFl = components_pressureError_errFl__components_Component_Automatic_calc;
      components_pressureError_errFr = components_pressureError_errFr__components_Component_Automatic_calc;
      components_pressureError_errRl = components_pressureError_errRl__components_Component_Automatic_calc;
      components_pressureError_errRr = components_pressureError_errRr__components_Component_Automatic_calc;
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_Component_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



