#ifndef _ASD_COMPONENTS_LIB_NOISEGENERATOR_AUTOMATIC_H_
#define _ASD_COMPONENTS_LIB_NOISEGENERATOR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_NoiseGenerator_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 15:16:58
*
* @brief   "components_lib_NoiseGenerator>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_lib_NoiseGenerator_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_lib_NoiseGenerator_Automatic_RAM_SUBSTRUCT {
   uint16 mem;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_lib_NoiseGenerator_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_lib_NoiseGenerator_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_lib_NoiseGenerator_Automatic {
   struct components_lib_NoiseGenerator_Automatic_RAM_SUBSTRUCT * components_lib_NoiseGenerator_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_lib_NoiseGenerator_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ....components_lib_NoiseGenerator_Automatic */
#define _components_lib_NoiseGenerator_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_lib_NoiseGenerator_Automatic
 ******************************************************************************/
extern float32 components_lib_NoiseGenerator_Automatic_calc (
               const struct components_lib_NoiseGenerator_Automatic * self,
   /* IN    */ const uint16                                           argA,
   /* IN    */ const uint16                                           argC,
   /* IN    */ const uint16                                           argM,
   /* IN    */ const float32                                          scaleGain
   );



#endif /* _ASD_COMPONENTS_LIB_NOISEGENERATOR_AUTOMATIC_H_ */
