#ifndef _COMPONENTS_VELOCAR_AUTOMATIC_H_
#define _COMPONENTS_VELOCAR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_veloCar_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_veloCar
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_veloCar_vfl_VAL components_veloCar_vfl
#define components_veloCar_vfr_VAL components_veloCar_vfr
#define components_veloCar_vrl_VAL components_veloCar_vrl
#define components_veloCar_vrr_VAL components_veloCar_vrr
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_VELOCAR_AUTOMATIC_H_ */
