/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_AverageTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    08.03.2019 17:48:32
*
* @brief   "components_lib_AverageTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_lib_AverageTest_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "TirePressureProject_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_lib_AverageTest'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_lib_AverageTest_Automatic_testavgOn4Inputs'
 * ----------------------------------------------------------------------------
 * model name:...................................'testavgOn4Inputs'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_lib_AverageTest_Automatic_testavgOn4Inputs (void)
{
   ASSERT_TRUE(components_lib_average_Automatic_avgOn4Inputs(1.0F, 1.0F, 1.0F, 1.0F) == 1.0F);
   ASSERT_FALSE(components_lib_average_Automatic_avgOn4Inputs(1.0F, 2.0F, 3.0F, 4.0F) == 20.0F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_lib_AverageTest_Automatic_testavgOn4Inputs'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



