#ifndef _COMPONENTS_DIFFWHEEL_AUTOMATIC_H_
#define _COMPONENTS_DIFFWHEEL_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_diffWheel_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_diffWheel
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_diffWheel_diffFl_VAL components_diffWheel_diffFl
#define components_diffWheel_diffFr_VAL components_diffWheel_diffFr
#define components_diffWheel_diffRl_VAL components_diffWheel_diffRl
#define components_diffWheel_diffRr_VAL components_diffWheel_diffRr
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_DIFFWHEEL_AUTOMATIC_H_ */
