#ifndef _ASD_COMPONENTS_LIB_PERCENTCOMPARE_AUTOMATIC_H_
#define _ASD_COMPONENTS_LIB_PERCENTCOMPARE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_percentCompare_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 15:16:58
*
* @brief   "components_lib_percentCompare>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for class COMPONENTS_LIB_PERCENTCOMPARE_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ....components_lib_percentCompare_Automatic */
#define _components_lib_percentCompare_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_lib_percentCompare_Automatic
 ******************************************************************************/
extern float32 components_lib_percentCompare_Automatic_calc (
   /* IN    */ const float32 value,
   /* IN    */ const float32 avg
   );



#endif /* _ASD_COMPONENTS_LIB_PERCENTCOMPARE_AUTOMATIC_H_ */
