/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_Integrator_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "components_lib_Integrator>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_lib_Integrator_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define kI_VAL (self->components_lib_Integrator_Automatic_CAL_MEM->kI)
#define memory_VAL (self->components_lib_Integrator_Automatic_RAM->memory)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_lib_Integrator_Automatic_integrate'
 * ----------------------------------------------------------------------------
 * model name:...................................'integrate'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_lib_Integrator_Automatic_integrate (
               const struct components_lib_Integrator_Automatic * self,
   /* IN    */ const float32                                      inputVal,
   /* IN    */ const float32                                      dtVal
   )
{
   memory_VAL = (inputVal * kI_VAL * dtVal) + memory_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_lib_Integrator_Automatic_integrate'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_lib_Integrator_Automatic_outVal'
 * ----------------------------------------------------------------------------
 * model name:...................................'outVal'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_lib_Integrator_Automatic_outVal ( const struct components_lib_Integrator_Automatic * self)
{
   return memory_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_lib_Integrator_Automatic_outVal'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



