#ifndef _COMPONENTS_PRESSUREERROR_AUTOMATIC_H_
#define _COMPONENTS_PRESSUREERROR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_pressureError_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_pressureError
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_pressureError_errFl_VAL components_pressureError_errFl
#define components_pressureError_errFr_VAL components_pressureError_errFr
#define components_pressureError_errRl_VAL components_pressureError_errRl
#define components_pressureError_errRr_VAL components_pressureError_errRr
#define components_pressureError_err_VAL components_pressureError_err
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_PRESSUREERROR_AUTOMATIC_H_ */
