#ifndef _COMPONENTS_LIB_DIFFCHECK_AUTOMATIC_H_
#define _COMPONENTS_LIB_DIFFCHECK_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_diffCheck_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_lib_diffCheck
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define border_VAL components_lib_diffCheck_CAL_MEM.border
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_LIB_DIFFCHECK_AUTOMATIC_H_ */
