#ifndef _ASD_COMPONENTS_LIB_AVERAGETEST_AUTOMATIC_H_
#define _ASD_COMPONENTS_LIB_AVERAGETEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_AverageTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    08.03.2019 17:48:32
*
* @brief   "components_lib_AverageTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_lib_average_Automatic.h"


/* component structure for module COMPONENTS_LIB_AVERAGETEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .......components_lib_AverageTest_Automatic */
#define _components_lib_AverageTest_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_lib_AverageTest_Automatic
 ******************************************************************************/
extern void components_lib_AverageTest_Automatic_testavgOn4Inputs (void);



#endif /* _ASD_COMPONENTS_LIB_AVERAGETEST_AUTOMATIC_H_ */
