/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_percentCompare_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    22.03.2019 16:43:33
*
* @brief   "components_lib_percentCompare>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_lib_percentCompare_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_lib_percentCompare_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_lib_percentCompare_Automatic_calc (
   /* IN    */ const float32 value,
   /* IN    */ const float32 avg
   )
{
   /* temp. variables */
   uint8 _t1uint8;
   float32 _t1real32;

   _t1uint8 = avg == 0.0F;
   if (_t1uint8)
   {
      return 0.0F;
   } /* end if */
   _t1real32 = value - avg;
   return ((_t1uint8) ? _t1real32 : (_t1real32 / avg));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_lib_percentCompare_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



