#ifndef _COMPONENTS_LIB_NOISEGENERATOR_AUTOMATIC_H_
#define _COMPONENTS_LIB_NOISEGENERATOR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_NoiseGenerator_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_lib_NoiseGenerator
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define mem_VAL self->components_lib_NoiseGenerator_Automatic_RAM->mem
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_LIB_NOISEGENERATOR_AUTOMATIC_H_ */
