#ifndef _COMPONENTS_LIB_STATEMASCHINE_AUTOMATIC_H_
#define _COMPONENTS_LIB_STATEMASCHINE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_lib_statemaschine_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_lib_statemaschine
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define SoundOutStateMaschine_instance_VAL components_lib_statemaschine.SoundOutStateMaschine_instance
#define SoundOutStateMaschine_instance_REF &(components_lib_statemaschine.SoundOutStateMaschine_instance)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_LIB_STATEMASCHINE_AUTOMATIC_H_ */
