#ifndef _ASD_INTEGRATORTEST_PC_AUTOMATIC_H_
#define _ASD_INTEGRATORTEST_PC_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    IntegratorTest_PC_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    08.03.2019 16:58:58
*
* @brief   "IntegratorTest_PC>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_lib_IntegratorTest_Automatic.h"


/* component structure for project INTEGRATORTEST_PC_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................IntegratorTest_PC_Automatic */
#define _IntegratorTest_PC_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project IntegratorTest_PC_Automatic
 ******************************************************************************/



#endif /* _ASD_INTEGRATORTEST_PC_AUTOMATIC_H_ */
