#ifndef _ASD_PC_PC_AUTOMATIC_H_
#define _ASD_PC_PC_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    PC_PC_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    20.03.2019 15:16:27
*
* @brief   "PC_PC>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_Component_Automatic.h"
#include "components_diffWheel_Automatic.h"
#include "components_distanceCar_Automatic.h"
#include "components_lib_diffCheck_Automatic.h"
#include "components_lib_IntegratorTest_Automatic.h"
#include "components_lib_statemaschine_Automatic.h"
#include "components_pressureError_Automatic.h"
#include "components_veloCar_Automatic.h"


/* component structure for project PC_PC_AUTOMATIC intentionally not created  */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............................PC_PC_Automatic */
#define _PC_PC_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project PC_PC_Automatic
 ******************************************************************************/



#endif /* _ASD_PC_PC_AUTOMATIC_H_ */
