/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    tests_diffCheckTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 15:57:42
*
* @brief   "tests_diffCheckTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "tests_diffCheckTest_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_lib_diffCheck_Automatic.h"
#include "TirePressureProject_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'tests_diffCheckTest'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'tests_diffCheckTest_Automatic_testOFDiffCheckInBoundNegative'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOFDiffCheckInBoundNegative'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void tests_diffCheckTest_Automatic_testOFDiffCheckInBoundNegative (void)
{
   ASSERT_FALSE(components_lib_diffCheck_Automatic_calc(-0.0005F));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'tests_diffCheckTest_Automatic_testOFDiffCheckInBoundNegative'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'tests_diffCheckTest_Automatic_testOFDiffCheckInBoundPositive'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOFDiffCheckInBoundPositive'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void tests_diffCheckTest_Automatic_testOFDiffCheckInBoundPositive (void)
{
   ASSERT_FALSE(components_lib_diffCheck_Automatic_calc(0.0005F));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'tests_diffCheckTest_Automatic_testOFDiffCheckInBoundPositive'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'tests_diffCheckTest_Automatic_testOFDiffCheckLower'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOFDiffCheckLower'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void tests_diffCheckTest_Automatic_testOFDiffCheckLower (void)
{
   ASSERT_TRUE(components_lib_diffCheck_Automatic_calc(-0.005F));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'tests_diffCheckTest_Automatic_testOFDiffCheckLower'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'tests_diffCheckTest_Automatic_testOFDiffCheckUpper'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOFDiffCheckUpper'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void tests_diffCheckTest_Automatic_testOFDiffCheckUpper (void)
{
   ASSERT_TRUE(components_lib_diffCheck_Automatic_calc(0.005F));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'tests_diffCheckTest_Automatic_testOFDiffCheckUpper'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



