#ifndef _ASD_TESTS_DIFFCHECKTEST_AUTOMATIC_H_
#define _ASD_TESTS_DIFFCHECKTEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    tests_diffCheckTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 15:57:42
*
* @brief   "tests_diffCheckTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module TESTS_DIFFCHECKTEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..............tests_diffCheckTest_Automatic */
#define _tests_diffCheckTest_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module tests_diffCheckTest_Automatic
 ******************************************************************************/
extern void tests_diffCheckTest_Automatic_testOFDiffCheckInBoundNegative (void);
extern void tests_diffCheckTest_Automatic_testOFDiffCheckInBoundPositive (void);
extern void tests_diffCheckTest_Automatic_testOFDiffCheckLower (void);
extern void tests_diffCheckTest_Automatic_testOFDiffCheckUpper (void);



#endif /* _ASD_TESTS_DIFFCHECKTEST_AUTOMATIC_H_ */
