#ifndef _ASD_TIREPRESSUREPROJECT_AUTOMATIC_H_
#define _ASD_TIREPRESSUREPROJECT_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    TirePressureProject_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    08.03.2019 17:48:32
*
* @brief   "TirePressureProject>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "assertLib_Assert_Impl.h"
#include "components_lib_AverageTest_Automatic.h"


/* component structure for project TIREPRESSUREPROJECT_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..............TirePressureProject_Automatic */
#define _TirePressureProject_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project TirePressureProject_Automatic
 ******************************************************************************/



#endif /* _ASD_TIREPRESSUREPROJECT_AUTOMATIC_H_ */
