/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Component_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_Component_Automatic
 *
 **/
#include "components_Component_Automatic.l1.h"
#include "components_Component_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_Component_Automatic (L1_components_Component_Automatic_Class* _ASCET_class)
{
    _ASCET_class->Landscape = initInstance_charTable1Wrapper((uint32)&components_Component_Landscape_VAL.xDist, sizeof(float32), (uint32)&components_Component_Landscape_VAL.values, sizeof(float32), /* dim */20, /* interpol kind */1, /* extrapol kind */0, ASD_PARAMETER);
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
static ASDClassHeader L1_components_Component_Automatic_ClassHeader = {
	0, 0, 10, 1, &_ObjectMethodList, &_ClassMethodList
};

L1_components_Component_Automatic_Class L1_components_Component_Automatic_ClassObj = {{1, {&L1_components_Component_Automatic_ClassHeader}, {0}}};

bool initialized_components_Component_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_Component_Automatic_Obj* initInstance_L1_components_Component_Automatic(const struct components_Component_Automatic* self)
{
    struct L1_components_Component_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_Component_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_Component_Automatic = true;
        initClass_L1_components_Component_Automatic(&L1_components_Component_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_Component_Automatic);
    L1_Instance->s = initInstance_scalarWrapper((uint32)&s_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->TrackSize = initInstance_scalarWrapper((uint32)&TrackSize_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->v = initInstance_scalarWrapper((uint32)&v_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->ds = initInstance_scalarWrapper((uint32)&ds_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->h = initInstance_scalarWrapper((uint32)&h_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->dh = initInstance_scalarWrapper((uint32)&dh_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->momentum = initInstance_scalarWrapper((uint32)&momentum_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->EngineMomentum = initInstance_columnDirCharTable2Wrapper((uint32)&EngineMomentum_VAL.xDist, sizeof(float32), (uint32)&EngineMomentum_VAL.yDist, sizeof(float32), (uint32)&EngineMomentum_VAL.values, sizeof(float32), /* dimX */6, /* dimY */6, /* interpol kind */1, /* extrapol kind */0, ASD_PARAMETER);
    L1_Instance->BrakeMomentum = initInstance_charTable1Wrapper((uint32)&BrakeMomentum_VAL.xDist, sizeof(float32), (uint32)&BrakeMomentum_VAL.values, sizeof(float32), /* dim */6, /* interpol kind */1, /* extrapol kind */0, ASD_PARAMETER);
    L1_Instance->AirFriction = initInstance_charTable1Wrapper((uint32)&AirFriction_VAL.xDist, sizeof(float32), (uint32)&AirFriction_VAL.values, sizeof(float32), /* dim */6, /* interpol kind */1, /* extrapol kind */0, ASD_PARAMETER);

    return L1_Instance;
}
