#ifndef _STRUCTURE_ASD_L1_components_Module_Automatic
#define _STRUCTURE_ASD_L1_components_Module_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Module_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_Module_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_Module_Automatic.h"
#include "components_Component_Automatic.l1.h"
#include "components_ACC_Automatic.l1.h"

/**
 * local variables object structure 
 **/
struct L1_components_Module_Automatic_Obj {
	ASDObjectHeader objectHeader;
	struct L1_components_Component_Automatic_Obj* Component_instance;
	struct L1_components_ACC_Automatic_Obj* ACC_instance;
	struct L1_components_ACC_Automatic_Obj* ACC_instance_3;
	scalarWrapper_Obj* trackPosition;
	scalarWrapper_Obj* dh;
	scalarWrapper_Obj* v;
	scalarWrapper_Obj* totalDistance;
	scalarWrapper_Obj* dtime;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_components_Module_Automatic_Class;

extern L1_components_Module_Automatic_Class L1_components_Module_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_Module_Automatic (L1_components_Module_Automatic_Class* _ASCET_class);
extern struct L1_components_Module_Automatic_Obj* initInstance_L1_components_Module_Automatic(void);
#endif /* _STRUCTURE_ASD_L1_components_Module_Automatic */
