#ifndef _STRUCTURE_ASD_L1_components_Driver_Automatic
#define _STRUCTURE_ASD_L1_components_Driver_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Driver_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_Driver_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_Driver_Automatic.h"

/**
 * local variables object structure 
 **/
struct L1_components_Driver_Automatic_Obj {
	ASDObjectHeader objectHeader;
	scalarWrapper_Obj* inGaspedPosition;
	scalarWrapper_Obj* inBreakpedPosition;
	scalarWrapper_Obj* accIsActive;
	scalarWrapper_Obj* accTargetSpeed;
	scalarWrapper_Obj* turnAccOn;
	scalarWrapper_Obj* turnAccOff;
	scalarWrapper_Obj* accState;
	scalarWrapper_Obj* newState;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_components_Driver_Automatic_Class;

extern L1_components_Driver_Automatic_Class L1_components_Driver_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_Driver_Automatic (L1_components_Driver_Automatic_Class* _ASCET_class);
extern struct L1_components_Driver_Automatic_Obj* initInstance_L1_components_Driver_Automatic(void);
#endif /* _STRUCTURE_ASD_L1_components_Driver_Automatic */
