#ifndef _STRUCTURE_ASD_L1_components_Component_Automatic
#define _STRUCTURE_ASD_L1_components_Component_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Component_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_Component_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_Component_Automatic.h"

/**
 * local variables object structure 
 **/
struct L1_components_Component_Automatic_Obj {
	ASDObjectHeader objectHeader;
	scalarWrapper_Obj* s;
	scalarWrapper_Obj* TrackSize;
	scalarWrapper_Obj* v;
	scalarWrapper_Obj* ds;
	scalarWrapper_Obj* h;
	scalarWrapper_Obj* dh;
	scalarWrapper_Obj* momentum;
	columnDirCharTable2Wrapper_Obj* EngineMomentum;
	charTable1Wrapper_Obj* BrakeMomentum;
	charTable1Wrapper_Obj* AirFriction;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
	charTable1Wrapper_Obj* Landscape;
} L1_components_Component_Automatic_Class;

extern L1_components_Component_Automatic_Class L1_components_Component_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_Component_Automatic (L1_components_Component_Automatic_Class* _ASCET_class);
extern struct L1_components_Component_Automatic_Obj* initInstance_L1_components_Component_Automatic(const struct components_Component_Automatic* self);
#endif /* _STRUCTURE_ASD_L1_components_Component_Automatic */
