/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Driver_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_Driver_Automatic
 *
 **/
#include "components_Driver_Automatic.l1.h"
#include "components_Driver_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_Driver_Automatic (L1_components_Driver_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_components_Driver_Automatic_Obj* L1_components_Driver_AutomaticInstance = NULL;

static ASDClassHeader L1_components_Driver_Automatic_ClassHeader = {
	0, 0, 8, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_Driver_Automatic_Class L1_components_Driver_Automatic_ClassObj = {{1, {&L1_components_Driver_Automatic_ClassHeader}, {0}}};

bool initialized_components_Driver_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_Driver_Automatic_Obj* initInstance_L1_components_Driver_Automatic(void)
{
    struct L1_components_Driver_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_Driver_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_Driver_Automatic = true;
        initClass_L1_components_Driver_Automatic(&L1_components_Driver_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_Driver_Automatic);
    L1_Instance->inGaspedPosition = initInstance_scalarWrapper((uint32)&inGaspedPosition_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->inBreakpedPosition = initInstance_scalarWrapper((uint32)&inBreakpedPosition_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->accIsActive = initInstance_scalarWrapper((uint32)&accIsActive_VAL, sizeof(uint8), ASD_PARAMETER);
    L1_Instance->accTargetSpeed = initInstance_scalarWrapper((uint32)&accTargetSpeed_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->turnAccOn = initInstance_scalarWrapper((uint32)&turnAccOn_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->turnAccOff = initInstance_scalarWrapper((uint32)&turnAccOff_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->accState = initInstance_scalarWrapper((uint32)&accState_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->newState = initInstance_scalarWrapper((uint32)&newState_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_components_Driver_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
