/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_accStateChange_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_accStateChange_Automatic
 *
 **/
#include "components_accStateChange_Automatic.l1.h"
#include "components_accStateChange_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_accStateChange_Automatic (L1_components_accStateChange_Automatic_Class* _ASCET_class)
{
    _ASCET_class->newState = initInstance_scalarWrapper((uint32)&components_accStateChange_newState_VAL, sizeof(uint8), ASD_VARIABLE);
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_components_accStateChange_Automatic_Obj* L1_components_accStateChange_AutomaticInstance = NULL;

static ASDClassHeader L1_components_accStateChange_Automatic_ClassHeader = {
	0, 0, 0, 1, &_ObjectMethodList, &_ClassMethodList
};

L1_components_accStateChange_Automatic_Class L1_components_accStateChange_Automatic_ClassObj = {{1, {&L1_components_accStateChange_Automatic_ClassHeader}, {0}}};

bool initialized_components_accStateChange_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_accStateChange_Automatic_Obj* initInstance_L1_components_accStateChange_Automatic(void)
{
    struct L1_components_accStateChange_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_accStateChange_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_accStateChange_Automatic = true;
        initClass_L1_components_accStateChange_Automatic(&L1_components_accStateChange_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_accStateChange_Automatic);
    L1_components_accStateChange_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
