/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_ACC_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_ACC_Automatic
 *
 **/
#include "components_ACC_Automatic.l1.h"
#include "components_ACC_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_ACC_Automatic (L1_components_ACC_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
static ASDClassHeader L1_components_ACC_Automatic_ClassHeader = {
	0, 0, 5, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_ACC_Automatic_Class L1_components_ACC_Automatic_ClassObj = {{1, {&L1_components_ACC_Automatic_ClassHeader}, {0}}};

bool initialized_components_ACC_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_ACC_Automatic_Obj* initInstance_L1_components_ACC_Automatic(const struct components_ACC_Automatic* self)
{
    struct L1_components_ACC_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_ACC_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_ACC_Automatic = true;
        initClass_L1_components_ACC_Automatic(&L1_components_ACC_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_ACC_Automatic);
    L1_Instance->prevGaspedPosition = initInstance_scalarWrapper((uint32)&prevGaspedPosition_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->prevBrakepedPosition = initInstance_scalarWrapper((uint32)&prevBrakepedPosition_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->accGaspedPosition = initInstance_scalarWrapper((uint32)&accGaspedPosition_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->accBrakepedPosition = initInstance_scalarWrapper((uint32)&accBrakepedPosition_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->isActive = initInstance_scalarWrapper((uint32)&isActive_VAL, sizeof(uint8), ASD_VARIABLE);

    return L1_Instance;
}
