#ifndef _STRUCTURE_ASD_L1_components_ACC_Automatic
#define _STRUCTURE_ASD_L1_components_ACC_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_ACC_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_ACC_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_ACC_Automatic.h"

/**
 * local variables object structure 
 **/
struct L1_components_ACC_Automatic_Obj {
	ASDObjectHeader objectHeader;
	scalarWrapper_Obj* prevGaspedPosition;
	scalarWrapper_Obj* prevBrakepedPosition;
	scalarWrapper_Obj* accGaspedPosition;
	scalarWrapper_Obj* accBrakepedPosition;
	scalarWrapper_Obj* isActive;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_components_ACC_Automatic_Class;

extern L1_components_ACC_Automatic_Class L1_components_ACC_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_ACC_Automatic (L1_components_ACC_Automatic_Class* _ASCET_class);
extern struct L1_components_ACC_Automatic_Obj* initInstance_L1_components_ACC_Automatic(const struct components_ACC_Automatic* self);
#endif /* _STRUCTURE_ASD_L1_components_ACC_Automatic */
