#ifndef _STRUCTURE_ASD_L1_TestDriver_PC
#define _STRUCTURE_ASD_L1_TestDriver_PC
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    TestDriver_PC.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: TestDriver_PC
 *
 **/
#include "a_basdef.h"
#include "components_DeltaTimeService_Automatic.l1.h"
#include "components_Driver_Automatic.l1.h"
#include "components_gaspedMessage_Automatic.l1.h"
#include "components_breakpedMessage_Automatic.l1.h"
#include "components_accStateChange_Automatic.l1.h"
#include "components_accMessage_Automatic.l1.h"
#include "components_Module_Automatic.l1.h"
#include "components_ContinuousTrack_Automatic.l1.h"

/**
 * local variables object structure 
 **/
struct L1_TestDriver_PC_Obj {
	ASDObjectHeader objectHeader;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
	struct L1_components_DeltaTimeService_Automatic_Obj* components_DeltaTimeService_Automatic;
	struct L1_components_Driver_Automatic_Obj* components_Driver_Automatic;
	struct L1_components_gaspedMessage_Automatic_Obj* components_gaspedMessage_Automatic;
	struct L1_components_breakpedMessage_Automatic_Obj* components_breakpedMessage_Automatic;
	struct L1_components_accStateChange_Automatic_Obj* components_accStateChange_Automatic;
	struct L1_components_accMessage_Automatic_Obj* components_accMessage_Automatic;
	struct L1_components_Module_Automatic_Obj* components_Module_Automatic;
	struct L1_components_ContinuousTrack_Automatic_Obj* components_ContinuousTrack_Automatic;
} L1_TestDriver_PC_Class;

extern L1_TestDriver_PC_Class L1_TestDriver_PC_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_TestDriver_PC (L1_TestDriver_PC_Class* _ASCET_class);
extern struct L1_TestDriver_PC_Obj* initInstance_L1_TestDriver_PC(void);
#endif /* _STRUCTURE_ASD_L1_TestDriver_PC */
