/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    TestDriver_PC.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for project L1 node: TestDriver_PC
 *
 **/
#include "TestDriver_PC.l1.h"
#include "TestDriver_PC.init.h"
#include "programId_TestDriver_PC.h"

/**
 * Class initialization 
 **/
void initClass_L1_TestDriver_PC (L1_TestDriver_PC_Class* _ASCET_class)
{
    _ASCET_class->components_DeltaTimeService_Automatic = initInstance_L1_components_DeltaTimeService_Automatic();
    _ASCET_class->components_Driver_Automatic = initInstance_L1_components_Driver_Automatic();
    _ASCET_class->components_gaspedMessage_Automatic = initInstance_L1_components_gaspedMessage_Automatic();
    _ASCET_class->components_breakpedMessage_Automatic = initInstance_L1_components_breakpedMessage_Automatic();
    _ASCET_class->components_accStateChange_Automatic = initInstance_L1_components_accStateChange_Automatic();
    _ASCET_class->components_accMessage_Automatic = initInstance_L1_components_accMessage_Automatic();
    _ASCET_class->components_Module_Automatic = initInstance_L1_components_Module_Automatic();
    _ASCET_class->components_ContinuousTrack_Automatic = initInstance_L1_components_ContinuousTrack_Automatic();
}

/**
 * L1 protocol functions 
 **/

static uint8 *_L1_getPid (ASDObject *self, uint8 *_ASCET_data)
{
    uint8 defineFlag = true;
    uint32 pid = UNIQUE_PROGRAM_ID;
    addScalar (_ASCET_data, (uint8 *)&pid, sizeof(uint32));
    addScalar (_ASCET_data, (uint8 *)&defineFlag, sizeof(defineFlag));
    return (_ASCET_data);
}

static uint8 *_L1_getNVid(ASDObject *self, uint8 *_ASCET_data)
{
    uint8 defineFlag = true;
    uint32 nvid = 0;
    addScalar (_ASCET_data, (uint8 *)&nvid, sizeof(nvid));
    addScalar (_ASCET_data, (uint8 *)&defineFlag, sizeof(defineFlag));
    return (_ASCET_data);
}

static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    _L1_getPid,
    _L1_getNVid
};

/**
 * Global objects 
 **/
struct L1_TestDriver_PC_Obj* L1_TestDriver_PCInstance = NULL;

static ASDClassHeader L1_TestDriver_PC_ClassHeader = {
	0, 2, 0, 8, &_ObjectMethodList, &_ClassMethodList
};

L1_TestDriver_PC_Class L1_TestDriver_PC_ClassObj = {{1, {&L1_TestDriver_PC_ClassHeader}, {0}}};

bool initialized_TestDriver_PC = false;

/**
 * Initialize this L1 component 
 **/
struct L1_TestDriver_PC_Obj* initInstance_L1_TestDriver_PC(void)
{
    struct L1_TestDriver_PC_Obj* L1_Instance = NULL;
    if (!initialized_TestDriver_PC) {
        /* for first time also static class data shall be initialized */
        initialized_TestDriver_PC = true;
        initClass_L1_TestDriver_PC(&L1_TestDriver_PC_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_TestDriver_PC);
    L1_TestDriver_PCInstance = L1_Instance;

    return L1_Instance;
}
