/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Component_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:29:25
*
* @brief   "components_Component>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Component_Automatic.h"
#include "ESDL_Linear_Interpolation.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



/******************************************************************************
 * BEGIN: DEFINITION OF CHARACTERISTIC TABLE 'components_Component_Landscape'
 * ---------------------------------------------------------------------------*/
struct CharTable1_real32_20_real32_TYPE components_Component_Landscape = {
      20U,
      {
         0.0F, 100.0F, 145.569620253165F, 202.53164556962F, 221.518987341772F, 240.0F,
         259.493670886076F, 300.0F, 350.0F, 400.0F, 450.0F, 500.0F, 600.0F, 700.0F,
         750.0F, 800.0F, 810.0F, 850.0F, 900.0F, 1000.0F
      },
      {
         0.0F, 4.0F, 7.125F, 10.375F, 10.75F, 10.5F, 9.0F, 5.375F, 2.625F, 0.625F, 1.25F,
         0.625F, 0.0F, 0.0F, 1.375F, 0.75F, 0.375F, 0.625F, 0.0F, 0.0F
      }
   };
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF CHARACTERISTIC TABLE 'components_Component_Landscape'
 ******************************************************************************/


#define AirFriction_REF (&(self->components_Component_Automatic_CAL_MEM->AirFriction))
#define BrakeMomentum_REF (&(self->components_Component_Automatic_CAL_MEM->BrakeMomentum))
#define components_Component_Landscape_REF (&(components_Component_Landscape))
#define dh_VAL (self->components_Component_Automatic_RAM->dh)
#define ds_VAL (self->components_Component_Automatic_RAM->ds)
#define EngineMomentum_REF (&(self->components_Component_Automatic_CAL_MEM->EngineMomentum))
#define h_VAL (self->components_Component_Automatic_RAM->h)
#define momentum_VAL (self->components_Component_Automatic_RAM->momentum)
#define s_VAL (self->components_Component_Automatic_RAM->s)
#define TrackSize_VAL (self->components_Component_Automatic_CAL_MEM->TrackSize)
#define v_VAL (self->components_Component_Automatic_RAM->v)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_Component_Automatic_calc (
               const struct components_Component_Automatic * self,
   /* IN    */ const float32                                 brake,
   /* IN    */ const float32                                 power,
   /* IN    */ const float32                                 dtime
   )
{
   ds_VAL = (v_VAL * dtime) / 3.6F;
   dh_VAL
      = h_VAL - ESDL_Linear_CharTable1_getAt_r32r32((components_Component_Landscape_REF)->xSize, (components_Component_Landscape_REF)->xDist, (components_Component_Landscape_REF)->values, s_VAL);
   h_VAL
      = ESDL_Linear_CharTable1_getAt_r32r32((components_Component_Landscape_REF)->xSize, (components_Component_Landscape_REF)->xDist, (components_Component_Landscape_REF)->values, s_VAL);
   momentum_VAL
      = ESDL_Linear_CharTable2_getAt_r32r32r32((EngineMomentum_REF)->xSize, (EngineMomentum_REF)->xDist, (EngineMomentum_REF)->ySize, (EngineMomentum_REF)->yDist, (EngineMomentum_REF)->values, power, v_VAL);
   v_VAL
      = ((ESDL_Linear_CharTable1_getAt_r32r32((BrakeMomentum_REF)->xSize, (BrakeMomentum_REF)->xDist, (BrakeMomentum_REF)->values, brake) + momentum_VAL + ESDL_Linear_CharTable1_getAt_r32r32((AirFriction_REF)->xSize, (AirFriction_REF)->xDist, (AirFriction_REF)->values, v_VAL) + ((((ds_VAL == 0.0F) ? dh_VAL : (dh_VAL / ds_VAL))) * 9.81F)) * dtime * 3.6F) + v_VAL;
   s_VAL = ds_VAL + s_VAL;
   if (s_VAL > TrackSize_VAL)
   {
      s_VAL = 0.0F;
   } /* end if */
   if (v_VAL < 0.0F)
   {
      v_VAL = 0.0F;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_calc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_get_dh'
 * ----------------------------------------------------------------------------
 * model name:...................................'get_dh'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_get_dh ( const struct components_Component_Automatic * self)
{
   return dh_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_get_dh'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_get_ds'
 * ----------------------------------------------------------------------------
 * model name:...................................'get_ds'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_get_ds ( const struct components_Component_Automatic * self)
{
   return ds_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_get_ds'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_get_v'
 * ----------------------------------------------------------------------------
 * model name:...................................'get_v'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_get_v ( const struct components_Component_Automatic * self)
{
   return v_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_get_v'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_getPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'getPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_getPosition ( const struct components_Component_Automatic * self)
{
   return s_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_getPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_getTracksize'
 * ----------------------------------------------------------------------------
 * model name:...................................'getTracksize'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_getTracksize ( const struct components_Component_Automatic * self)
{
   return TrackSize_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_getTracksize'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



