#ifndef _COMPONENTS_ACC_AUTOMATIC_H_
#define _COMPONENTS_ACC_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ACC_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_ACC
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define prevGaspedPosition_VAL self->components_ACC_Automatic_RAM->prevGaspedPosition
#define prevBrakepedPosition_VAL self->components_ACC_Automatic_RAM->prevBrakepedPosition
#define accGaspedPosition_VAL self->components_ACC_Automatic_RAM->accGaspedPosition
#define accBrakepedPosition_VAL self->components_ACC_Automatic_RAM->accBrakepedPosition
#define isActive_VAL self->components_ACC_Automatic_RAM->isActive
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_ACC_AUTOMATIC_H_ */
