#ifndef _ASD_COMPONENTS_ACC_AUTOMATIC_H_
#define _ASD_COMPONENTS_ACC_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ACC_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:29:25
*
* @brief   "components_ACC>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_ACC_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_ACC_Automatic_RAM_SUBSTRUCT {
   float32 accBrakepedPosition;
   float32 accGaspedPosition;
   float32 prevBrakepedPosition;
   float32 prevGaspedPosition;
   uint8 isActive;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_ACC_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_ACC_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_ACC_Automatic {
   struct components_ACC_Automatic_RAM_SUBSTRUCT * components_ACC_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_ACC_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...................components_ACC_Automatic */
#define _components_ACC_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_ACC_Automatic
 ******************************************************************************/
extern void components_ACC_Automatic_calc (
               const struct components_ACC_Automatic * self,
   /* IN    */ const uint8                             esdl_calc_isActive,
   /* IN    */ const float32                           brakepedPosition,
   /* IN    */ const float32                           gaspedPosition,
   /* IN    */ const float32                           v,
   /* IN    */ const float32                           targetSpeed
   );
extern float32 components_ACC_Automatic_getBrakepedPosition ( const struct components_ACC_Automatic * self);
extern float32 components_ACC_Automatic_getGaspedPosition ( const struct components_ACC_Automatic * self);
extern uint8 components_ACC_Automatic_getIsActive ( const struct components_ACC_Automatic * self);
void components_ACC_Automatic_setBrakepedPosition (
               const struct components_ACC_Automatic * self,
   /* IN    */ const float32                           position
   );
void components_ACC_Automatic_setGaspedPosition (
               const struct components_ACC_Automatic * self,
   /* IN    */ const float32                           position
   );



#endif /* _ASD_COMPONENTS_ACC_AUTOMATIC_H_ */
