#ifndef _ASD_COMPONENTS_ACCSTATECHANGE_AUTOMATIC_H_
#define _ASD_COMPONENTS_ACCSTATECHANGE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_accStateChange_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:29:25
*
* @brief   "components_accStateChange>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/* component structure for module COMPONENTS_ACCSTATECHANGE_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ........components_accStateChange_Automatic */
#define _components_accStateChange_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_accStateChange_Automatic
 ******************************************************************************/


/* declaration of messages */
extern uint8 components_accStateChange_newState;


#endif /* _ASD_COMPONENTS_ACCSTATECHANGE_AUTOMATIC_H_ */
