#ifndef _COMPONENTS_ACCMESSAGE_AUTOMATIC_H_
#define _COMPONENTS_ACCMESSAGE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_accMessage_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_accMessage
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_accMessage_accIsActive_VAL components_accMessage_accIsActive
#define components_accMessage_accTargetSpeed_VAL components_accMessage_accTargetSpeed
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_ACCMESSAGE_AUTOMATIC_H_ */
