#ifndef _COMPONENTS_ACCSTATECHANGE_AUTOMATIC_H_
#define _COMPONENTS_ACCSTATECHANGE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_accStateChange_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_accStateChange
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_accStateChange_newState_VAL components_accStateChange_newState
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_ACCSTATECHANGE_AUTOMATIC_H_ */
