#ifndef _COMPONENTS_DRIVER_AUTOMATIC_H_
#define _COMPONENTS_DRIVER_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Driver_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Driver
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define inGaspedPosition_VAL components_Driver_CAL_MEM.inGaspedPosition
#define inBreakpedPosition_VAL components_Driver_CAL_MEM.inBreakpedPosition
#define accIsActive_VAL components_Driver_CAL_MEM.accIsActive
#define accTargetSpeed_VAL components_Driver_CAL_MEM.accTargetSpeed
#define turnAccOn_VAL components_Driver_RAM.turnAccOn
#define turnAccOff_VAL components_Driver_RAM.turnAccOff
#define accState_VAL components_Driver_RAM.accState
#define newState_VAL components_Driver_RAM.newState
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_DRIVER_AUTOMATIC_H_ */
