/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Module_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:29:25
*
* @brief   "components_Module>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Module_Automatic.h"
#include "components_accMessage_Automatic.h"
#include "components_breakpedMessage_Automatic.h"
#include "components_ContinuousTrack_Automatic.h"
#include "components_gaspedMessage_Automatic.h"
#include "TestDriver_PC_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Module_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_Module'
 * data set:.....................................'COMPONENTS_MODULE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Module_Automatic_CAL_MEM_SUBSTRUCT components_Module_CAL_MEM = {
   /* substruct: components_Module_CAL_MEM.Component_instance (modeled as:'Component_instance.components_Module') */
   {
      /* struct element:'components_Module_CAL_MEM.Component_instance.TrackSize' (modeled as:'TrackSize.Component_instance.components_Module') */
      1000.0F,
      /* struct element:'components_Module_CAL_MEM.Component_instance.AirFriction' (modeled as:'AirFriction.Component_instance.components_Module') */
      {
         6U,
         {
            0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
         },
         {
            0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
         }
      },
      /* struct element:'components_Module_CAL_MEM.Component_instance.BrakeMomentum' (modeled as:'BrakeMomentum.Component_instance.components_Module') */
      {
         6U,
         {
            0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
         }
      },
      /* struct element:'components_Module_CAL_MEM.Component_instance.EngineMomentum' (modeled as:'EngineMomentum.Component_instance.components_Module') */
      {
         6U,
         6U,
         {
            0.0F, 5.0F, 20.0F, 60.126582278481F, 80.0F, 100.0F
         },
         {
            0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
         },
         {
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            8.49999999999999e-1F, 0.6F, 0.3F, 0.0F, 0.0F, 0.0F,
            3.15F, 2.35F, 1.55F, 8.00000000000001e-1F, 3.99999999999999e-1F, 0.0F,
            4.5F, 3.6F, 2.7F, 1.5F, 0.9F, 0.0F,
            5.0F, 4.5F, 3.8F, 2.8F, 1.9F, 0.0F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Module_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Module_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Module'
 * data set:.....................................'COMPONENTS_MODULE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Module_Automatic_RAM_SUBSTRUCT components_Module_RAM = {
   /* struct element:'components_Module_RAM.dh' (modeled as:'dh.components_Module') */
   0.0F,
   /* struct element:'components_Module_RAM.dtime' (modeled as:'dtime.components_Module') */
   0.0F,
   /* struct element:'components_Module_RAM.totalDistance' (modeled as:'totalDistance.components_Module') */
   0.0F,
   /* struct element:'components_Module_RAM.trackPosition' (modeled as:'trackPosition.components_Module') */
   0.0F,
   /* struct element:'components_Module_RAM.v' (modeled as:'v.components_Module') */
   0.0F,
   /* substruct: components_Module_RAM.ACC_instance (modeled as:'ACC_instance.components_Module') */
   {
      /* struct element:'components_Module_RAM.ACC_instance.accBrakepedPosition' (modeled as:'accBrakepedPosition.ACC_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.ACC_instance.accGaspedPosition' (modeled as:'accGaspedPosition.ACC_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.ACC_instance.prevBrakepedPosition' (modeled as:'prevBrakepedPosition.ACC_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.ACC_instance.prevGaspedPosition' (modeled as:'prevGaspedPosition.ACC_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.ACC_instance.isActive' (modeled as:'isActive.ACC_instance.components_Module') */
      false
   },
   /* substruct: components_Module_RAM.ACC_instance_3 (modeled as:'ACC_instance_3.components_Module') */
   {
      /* struct element:'components_Module_RAM.ACC_instance_3.accBrakepedPosition' (modeled as:'accBrakepedPosition.ACC_instance_3.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.ACC_instance_3.accGaspedPosition' (modeled as:'accGaspedPosition.ACC_instance_3.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.ACC_instance_3.prevBrakepedPosition' (modeled as:'prevBrakepedPosition.ACC_instance_3.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.ACC_instance_3.prevGaspedPosition' (modeled as:'prevGaspedPosition.ACC_instance_3.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.ACC_instance_3.isActive' (modeled as:'isActive.ACC_instance_3.components_Module') */
      false
   },
   /* substruct: components_Module_RAM.Component_instance (modeled as:'Component_instance.components_Module') */
   {
      /* struct element:'components_Module_RAM.Component_instance.dh' (modeled as:'dh.Component_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.Component_instance.ds' (modeled as:'ds.Component_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.Component_instance.h' (modeled as:'h.Component_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.Component_instance.momentum' (modeled as:'momentum.Component_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.Component_instance.s' (modeled as:'s.Component_instance.components_Module') */
      0.0F,
      /* struct element:'components_Module_RAM.Component_instance.v' (modeled as:'v.Component_instance.components_Module') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Module_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_Module'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Module'
 * data set:.....................................'COMPONENTS_MODULE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_Module_Automatic components_Module = {
   /* substruct: components_Module.ACC_instance (modeled as:'ACC_instance.components_Module') */
   {
      /* type descriptor pointer 'components_ACC_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Module_RAM.ACC_instance
   },
   /* substruct: components_Module.ACC_instance_3 (modeled as:'ACC_instance_3.components_Module') */
   {
      /* type descriptor pointer 'components_ACC_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Module_RAM.ACC_instance_3
   },
   /* substruct: components_Module.Component_instance (modeled as:'Component_instance.components_Module') */
   {
      /* type descriptor pointer 'components_Component_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Module_CAL_MEM.Component_instance,
      /* type descriptor pointer 'components_Component_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Module_RAM.Component_instance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_Module'
 ******************************************************************************/





#define ACC_instance_3_REF (&(components_Module.ACC_instance_3))
#define Component_instance_REF (&(components_Module.Component_instance))
#define dh_VAL (components_Module_RAM.dh)
#define dT_VAL (ASD_DT_SCALED)
#define totalDistance_VAL (components_Module_RAM.totalDistance)
#define trackPosition_VAL (components_Module_RAM.trackPosition)
#define v_VAL (components_Module_RAM.v)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_Module_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void components_Module_Automatic_calc (void)
{
   /* define local message copies */
   uint8 components_accMessage_accIsActive__components_Module_Automatic_calc;
   float32 components_accMessage_accTargetSpeed__components_Module_Automatic_calc;
   float32 components_breakpedMessage_breakpedPosition__components_Module_Automatic_calc;
   float32 components_gaspedMessage_gaspedPosition__components_Module_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      components_accMessage_accIsActive__components_Module_Automatic_calc = components_accMessage_accIsActive;
      components_accMessage_accTargetSpeed__components_Module_Automatic_calc = components_accMessage_accTargetSpeed;
      components_breakpedMessage_breakpedPosition__components_Module_Automatic_calc = components_breakpedMessage_breakpedPosition;
      components_gaspedMessage_gaspedPosition__components_Module_Automatic_calc = components_gaspedMessage_gaspedPosition;
      EnableAllInterrupts();
   }
   trackPosition_VAL
      = components_ContinuousTrack_Automatic_getTrackPosition(components_Component_Automatic_getPosition(Component_instance_REF), components_Component_Automatic_get_ds(Component_instance_REF), components_Component_Automatic_getTracksize(Component_instance_REF));
   dh_VAL
      = components_Component_Automatic_get_dh(Component_instance_REF);
   v_VAL = components_Component_Automatic_get_v(Component_instance_REF);
   totalDistance_VAL = components_ContinuousTrack_Automatic_getTotalDistance();
   components_Component_Automatic_calc(Component_instance_REF, components_ACC_Automatic_getBrakepedPosition(ACC_instance_3_REF), components_ACC_Automatic_getGaspedPosition(ACC_instance_3_REF), dT_VAL);
   components_ACC_Automatic_calc(ACC_instance_3_REF, components_accMessage_accIsActive__components_Module_Automatic_calc, components_breakpedMessage_breakpedPosition__components_Module_Automatic_calc, components_gaspedMessage_gaspedPosition__components_Module_Automatic_calc, components_Component_Automatic_get_v(Component_instance_REF), components_accMessage_accTargetSpeed__components_Module_Automatic_calc);
   components_accMessage_accIsActive__components_Module_Automatic_calc = components_ACC_Automatic_getIsActive(ACC_instance_3_REF);
   /* send messages implicitly */
   {
      components_accMessage_accIsActive = components_accMessage_accIsActive__components_Module_Automatic_calc;
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_Module_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



