#ifndef _ASD_COMPONENTS_DRIVER_AUTOMATIC_H_
#define _ASD_COMPONENTS_DRIVER_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Driver_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:29:25
*
* @brief   "components_Driver>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Driver_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_Driver_Automatic_CAL_MEM_SUBSTRUCT {
   float32 accTargetSpeed;
   float32 inBreakpedPosition;
   float32 inGaspedPosition;
   uint8 accIsActive;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Driver_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Driver_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_Driver_Automatic_RAM_SUBSTRUCT {
   uint8 accState;
   uint8 newState;
   uint8 turnAccOff;
   uint8 turnAccOn;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_Driver_Automatic'
 ******************************************************************************/


/* component structure for module COMPONENTS_DRIVER_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................components_Driver_Automatic */
#define _components_Driver_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_Driver_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct components_Driver_Automatic_CAL_MEM_SUBSTRUCT components_Driver_CAL_MEM;

/* forward declaration of substruct variable 'components_Driver_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_Driver_Automatic_RAM_SUBSTRUCT components_Driver_RAM;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_Driver_Automatic
 ******************************************************************************/
extern void components_Driver_Automatic_setAcc (void);
extern void components_Driver_Automatic_drive (void);



#endif /* _ASD_COMPONENTS_DRIVER_AUTOMATIC_H_ */
