#ifndef _COMPONENTS_CONTINUOUSTRACK_AUTOMATIC_H_
#define _COMPONENTS_CONTINUOUSTRACK_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ContinuousTrack_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_ContinuousTrack
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define totalDistance_VAL components_ContinuousTrack_RAM.totalDistance
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_CONTINUOUSTRACK_AUTOMATIC_H_ */
