#ifndef _COMPONENTS_GASPEDMESSAGE_AUTOMATIC_H_
#define _COMPONENTS_GASPEDMESSAGE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_gaspedMessage_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_gaspedMessage
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_gaspedMessage_gaspedPosition_VAL components_gaspedMessage_gaspedPosition
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_GASPEDMESSAGE_AUTOMATIC_H_ */
