#ifndef _COMPONENTS_MODULE_AUTOMATIC_H_
#define _COMPONENTS_MODULE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Module_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Module
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define trackPosition_VAL components_Module_RAM.trackPosition
#define Component_instance_VAL components_Module.Component_instance
#define Component_instance_REF &(components_Module.Component_instance)
#define dh_VAL components_Module_RAM.dh
#define v_VAL components_Module_RAM.v
#define totalDistance_VAL components_Module_RAM.totalDistance
#define dtime_VAL components_Module_RAM.dtime
#define ACC_instance_VAL components_Module.ACC_instance
#define ACC_instance_REF &(components_Module.ACC_instance)
#define ACC_instance_3_VAL components_Module.ACC_instance_3
#define ACC_instance_3_REF &(components_Module.ACC_instance_3)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_MODULE_AUTOMATIC_H_ */
