#ifndef _COMPONENTS_BREAKPEDMESSAGE_AUTOMATIC_H_
#define _COMPONENTS_BREAKPEDMESSAGE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_breakpedMessage_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_breakpedMessage
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_breakpedMessage_breakpedPosition_VAL components_breakpedMessage_breakpedPosition
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_BREAKPEDMESSAGE_AUTOMATIC_H_ */
