#ifndef _COMPONENTS_COMPONENT_AUTOMATIC_H_
#define _COMPONENTS_COMPONENT_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Component_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Component
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define s_VAL self->components_Component_Automatic_RAM->s
#define TrackSize_VAL self->components_Component_Automatic_CAL_MEM->TrackSize
#define v_VAL self->components_Component_Automatic_RAM->v
#define ds_VAL self->components_Component_Automatic_RAM->ds
#define h_VAL self->components_Component_Automatic_RAM->h
#define dh_VAL self->components_Component_Automatic_RAM->dh
#define momentum_VAL self->components_Component_Automatic_RAM->momentum
#define EngineMomentum_VAL self->components_Component_Automatic_CAL_MEM->EngineMomentum
#define EngineMomentum_REF &(self->components_Component_Automatic_CAL_MEM->EngineMomentum)
#define BrakeMomentum_VAL self->components_Component_Automatic_CAL_MEM->BrakeMomentum
#define BrakeMomentum_REF &(self->components_Component_Automatic_CAL_MEM->BrakeMomentum)
#define AirFriction_VAL self->components_Component_Automatic_CAL_MEM->AirFriction
#define AirFriction_REF &(self->components_Component_Automatic_CAL_MEM->AirFriction)
#define components_Component_Landscape_VAL components_Component_Landscape
#define components_Component_Landscape_REF &(components_Component_Landscape)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_COMPONENT_AUTOMATIC_H_ */
