/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ACC_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:29:25
*
* @brief   "components_ACC>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_ACC_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define accBrakepedPosition_VAL (self->components_ACC_Automatic_RAM->accBrakepedPosition)
#define accGaspedPosition_VAL (self->components_ACC_Automatic_RAM->accGaspedPosition)
#define isActive_VAL (self->components_ACC_Automatic_RAM->isActive)
#define prevBrakepedPosition_VAL (self->components_ACC_Automatic_RAM->prevBrakepedPosition)
#define prevGaspedPosition_VAL (self->components_ACC_Automatic_RAM->prevGaspedPosition)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_ACC_Automatic_calc (
               const struct components_ACC_Automatic * self,
   /* IN    */ const uint8                             esdl_calc_isActive,
   /* IN    */ const float32                           brakepedPosition,
   /* IN    */ const float32                           gaspedPosition,
   /* IN    */ const float32                           v,
   /* IN    */ const float32                           targetSpeed
   )
{
   isActive_VAL = esdl_calc_isActive;
   if (!esdl_calc_isActive)
   {
      prevBrakepedPosition_VAL = brakepedPosition;
      prevGaspedPosition_VAL = gaspedPosition;
      accBrakepedPosition_VAL = brakepedPosition;
      accGaspedPosition_VAL = gaspedPosition;
      return;
   } /* end if */
   if (prevBrakepedPosition_VAL != brakepedPosition)
   {
      isActive_VAL = false;
      return;
   } /* end if */
   if (prevGaspedPosition_VAL != gaspedPosition)
   {
      components_ACC_Automatic_setGaspedPosition(self, gaspedPosition);
      return;
   } /* end if */
   prevBrakepedPosition_VAL = brakepedPosition;
   prevGaspedPosition_VAL = gaspedPosition;
   if (v > (targetSpeed * 1.01F))
   {
      components_ACC_Automatic_setBrakepedPosition(self, 100.0F);
   } /* end if */
   if (v < (targetSpeed * 0.99F))
   {
      components_ACC_Automatic_setGaspedPosition(self, 100.0F);
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Automatic_calc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Automatic_getBrakepedPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'getBrakepedPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_ACC_Automatic_getBrakepedPosition ( const struct components_ACC_Automatic * self)
{
   return accBrakepedPosition_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Automatic_getBrakepedPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Automatic_getGaspedPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'getGaspedPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_ACC_Automatic_getGaspedPosition ( const struct components_ACC_Automatic * self)
{
   return accGaspedPosition_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Automatic_getGaspedPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Automatic_getIsActive'
 * ----------------------------------------------------------------------------
 * model name:...................................'getIsActive'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 components_ACC_Automatic_getIsActive ( const struct components_ACC_Automatic * self)
{
   return isActive_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Automatic_getIsActive'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Automatic_setBrakepedPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'setBrakepedPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_ACC_Automatic_setBrakepedPosition (
               const struct components_ACC_Automatic * self,
   /* IN    */ const float32                           position
   )
{
   accGaspedPosition_VAL = 0.0F;
   accBrakepedPosition_VAL = position;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Automatic_setBrakepedPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Automatic_setGaspedPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'setGaspedPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_ACC_Automatic_setGaspedPosition (
               const struct components_ACC_Automatic * self,
   /* IN    */ const float32                           position
   )
{
   accGaspedPosition_VAL = position;
   accBrakepedPosition_VAL = 0.0F;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Automatic_setGaspedPosition'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



