#ifndef _ASD_TESTDRIVER_PC_AUTOMATIC_H_
#define _ASD_TESTDRIVER_PC_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    TestDriver_PC_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    21.03.2019 13:29:25
*
* @brief   "TestDriver_PC>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"
#include "components_accMessage_Automatic.h"
#include "components_accStateChange_Automatic.h"
#include "components_breakpedMessage_Automatic.h"
#include "components_ContinuousTrack_Automatic.h"
#include "components_DeltaTimeService_Automatic.h"
#include "components_Driver_Automatic.h"
#include "components_gaspedMessage_Automatic.h"
#include "components_Module_Automatic.h"


/* component structure for project TESTDRIVER_PC_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ....................TestDriver_PC_Automatic */
#define _TestDriver_PC_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project TestDriver_PC_Automatic
 ******************************************************************************/



#endif /* _ASD_TESTDRIVER_PC_AUTOMATIC_H_ */
